### ISSUE TITLE
Win Counters Not Correct

### ISSUE THREAD

**Issue by vbaileytopcoder** [appirio-tech/topcoder-app#1000]
Counters are not correct on this page:

https://www.topcoder.com/members/thomaskranitsas/details/?track=DEVELOP&subTrack=CODE&tab=challenges  

If you check the above link you will see that the counter says 11 wins but if you count the challenges he won you will count 12.

This is not the only example of this:

https://www.topcoder.com/members/thomaskranitsas/details/?track=DEVELOP&subTrack=FIRST_2_FINISH&tab=challenges

Mentions 15 wins when there were actually 17.

**Comment by birdofpreyru** [comment]
@ajefts It looks like backend problem to me. I've tracked the network communication, and it looks like TC API v3 returns incorrect count of victories, when `/members/{handle}/stats` endpoint is envoked. To deal with it within the BugBash, we need brief instructions where that API is and how do we handle related development (if it is a part of the legacy tc site, I know the answer is `it is complicated` :)

**Comment by birdofpreyru** [comment]
@ajefts I am not sure, but looking at win counters, I feel like they have just stuck and stopped counting further a week or few ago. Probably, you should just reboot something in the backend, if it makes sense?

**Comment by vbaileytopcoder** [comment]
@ajefts  is there anything I can do to move this one?

**Comment by birdofpreyru** [comment]
@ajefts It looks like statistics still are not being updated :(
