### ISSUE TITLE
[$10] - blog feed is not loading on my-dashboard

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1001]
The blog feed is not loading on the dashboard page.  I updated the feed URL to https://www.topcoder.com/feed/ in webpack, but it doesn't seem to be working still.

**Comment by ajefts** [comment]
@birdofpreyru Can you put this one on the list?

**Comment by birdofpreyru** [comment]
### Expected Fix
The Blog feed should be displayed in the Dashboard in the corresponding section in the bottom. Now it just always shows the loading indicator there:
![scr-05](https://cloud.githubusercontent.com/assets/20144632/22975386/da285fae-f386-11e6-9acc-73ac368b5d66.png)
Probably, it is just a small problem with the configuration.

**Comment by birdofpreyru** [comment]
@lijulat Any update?

**Comment by lijulat** [comment]
@birdofpreyru Apologies I haven't had the time to look at this yet. I am currently caught up in some other tasks which prevents me from taking this up any time soon.
