### ISSUE TITLE
[$20] - Color of the Complete Appeals button

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#1003]
Recently we have added `Complete Appeals` button to the challenge listing in the dashboard (https://github.com/appirio-tech/topcoder-app/pull/992, not yet in prod). Currently it is styled as any other button in the challenge card: white background, blue text, blue border in the regular state; blue background, white text in the hovered state.

As completing appeals too early may change contenstant's destinity, and thus potentially dangerous operation, let's change the color being used in this button from blue to the reddish `#e66`.

**Comment by birdofpreyru** [comment]
@ThomasKranitsas How do you build `topcoder-app` so that it uses the stylesheet from the updated version of `tc-site` repo?

**Comment by ThomasKranitsas** [comment]
@birdofpreyru I've no idea 😛 I just found where the css code for that button is and I updated it

**Comment by birdofpreyru** [comment]
@ThomasKranitsas You might found it wrong :-P After some inverstigation, I tend to believe that `topcoder-app` imports button styles (and some other styling) from `styles` repo (my best understanding, though I also might be wrong, as relations between different repos hosting different parts of tc are still quite a puzzle for me). Though, there is a problem: the first thing I see in `styles` repo is the warning `DEPRICATED! DO NOT USE!`.

I think, we should move the styling related to this ticket into `topcoder-app`, probably along with some related styling. But I would like to hear from @ajefts about it (whether I am right, and whether moving it to `topcoder-app` is a good idea, or there are some other plans at TC about it).

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Actually, as the stylesheets in `topcoder-app` override (I believe) those imported from other repos anyway, let's just add the style for `tc-btn-appeal` class to `topcoder-app/assets/css/my-dashboard/my-dashboard.scss` (or `.../my-challenges.scss`, if it is more appropriate). This way we resolve this issue in a secure way, and if we have any other input on styles, etc. we'll open new tickets.

**Comment by ThomasKranitsas** [comment]
Okay.. I'll do that later today

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Any update?

**Comment by birdofpreyru** [comment]
Hey @ThomasKranitsas, how are you doing? :)

Are you still planning to finish this one? I am preparing to start another Bug Bash this weekend. If you are not interested in this ticket anymore, I'll open it for that Bug Bash.

**Comment by ThomasKranitsas** [comment]
Hey @birdofpreyru, I completely forgot about this one.. I was extremely busy..
Sure you can open it for the next Bug Bash as I don't have enough time to fix it today.

Sorry and thanks for your understanding!

**Comment by birdofpreyru** [comment]
### Update
This is still should be done. The styling should reside in `topcoder-app` repo, and should not be specific to the `Complete Appeals` button (i.e. don't name corresponding class after that button, call it something like `btn-danger`, as we'll have another buttons using this color scheme).

**Comment by Savvas-cl** [comment]
@birdofpreyru pls give me permission so I can self-assign and change labels. Thank you.

**Comment by birdofpreyru** [comment]
@Savvas-cl Permissions granted

**Comment by Savvas-cl** [comment]
@birdofpreyru  as it will be a non-specific to challenges button styling. I think that the most appropriate place to put the css styling is in this file: 
topcoder-app/node-modules/appirio-styles/styles/topcoder/_tc-buttons.scss

Is this okay?

**Comment by birdofpreyru** [comment]
@Savvas-cl: Nope, because the first thing I see when open that repo (https://github.com/appirio-tech/styles) is `DEPRICATED! DO NOT USE!`.

Please, just put the new style into this repo.

**Comment by Savvas-cl** [comment]
so in either of the following two is it okay?
/css/my-dashboard/my-dashboard.scss (or .../my-challenges.scss)

**Comment by birdofpreyru** [comment]
Should be in the same file, where the challenge tiles for the Dashboard are styled.
It looks to me, that they are styled in the .../assets/css/directives/challenge-tile.scss,
but, please, double-check.

**Comment by Savvas-cl** [comment]
Yes that was the other option I had. I did not want to put it there because no other button related styling lies there. But I think its okay. Thanks.
