### ISSUE TITLE
[$25] Add cognitive banner to my-dashboard

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1007]
We need to add the banner from https://drive.google.com/drive/folders/0Bza1qtSwQr8UTzdHLUc1QUtObU0 to the my-dashboard page.  This should be placed above the Predix banner.

"Learn More" needs to be a link to https://cognitive.topcoder.com

As much as possible, please make the text editable in the code in the same way the other banners are setup.

Please also remove the TCO16 banner.

**Comment by ajefts** [comment]
@birdofpreyru Think we could do this one ASAP?

**Comment by rrandom** [comment]
I will take this one
