### ISSUE TITLE
New Listings - checkbox filters improvement

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1020]
When I click the checkbox filters for design/dev/data, I have to hit the magnifying glass in order to invoke the fitler. Should it just filter upon clicking the checkboxes? Also, I think they should be defaulted to selected.

**Comment by birdofpreyru** [comment]
Also done, but not merged. There were two parallel challenges this week, related to the new listing page. The one I have participated and won, have fixed a bunch of staff related to the filtering, but the code should have a bunch of conflicts with the results from other challenge :(
