### ISSUE TITLE
feedback - Visual fixes

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1044]
**Comment**: Read my notes
[Open #1 in Usersnap Dashboard](https://usersnap.com/a/#/topcoder-team/p/topcoder-challen-7ac17f85/1)
**Notes**:
 - This is not yet fixed - the empty state can't be read
 - The filters should not take into account the on/off state of track switches; or search bar.

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-20/21-28/47a6cac0-72f9-4bf7-8f43-d460a2c02cdc.png'>![feedback - Visual fixes](https://usersnappublic.s3.amazonaws.com/2017-02-20/21-28/b74fac38-52c3-46d5-a9e2-0837309c975d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-20/21-28/47a6cac0-72f9-4bf7-8f43-d460a2c02cdc.png'>Download original image</a>

**Browser**: Safari 10 (macOS Sierra)
**Referer**: [https://www.topcoder-dev.com/listings/#WyJXeUpYZVVscFRFTktkV1JYZUhOSmFYZHBTV2wzYVdKdVZuTmlRMGx6U1dsS1pDSXNJbVJoZEdGelkya3NaR1Z6YVdkdUlsMD0iLCJXeUpYZVVwWVpWVnNjRlJGVGt0a1YxSllaVWhPU21GWVpIQlRWMnd6WVZkS2RWWnVUbWxSTUd4NlUxZHNTMXBEU1hOSmJWSm9aRWRHZWxreWEzTmFSMVo2WVZka2RVeEhVbXhrYlZaellqTkJhVmhSUFQwaUxDSkJiR3dnUTJoaGJHeGxibWRsY3lJc0lrRnNiQ0JEYUdGc2JHVnVaMlZ6SWl3aVFXeHNJRU5vWVd4c1pXNW5aWE1pWFE9PSJd](https://www.topcoder-dev.com/listings/#WyJXeUpYZVVscFRFTktkV1JYZUhOSmFYZHBTV2wzYVdKdVZuTmlRMGx6U1dsS1pDSXNJbVJoZEdGelkya3NaR1Z6YVdkdUlsMD0iLCJXeUpYZVVwWVpWVnNjRlJGVGt0a1YxSllaVWhPU21GWVpIQlRWMnd6WVZkS2RWWnVUbWxSTUd4NlUxZHNTMXBEU1hOSmJWSm9aRWRHZWxreWEzTmFSMVo2WVZka2RVeEhVbXhrYlZaellqTkJhVmhSUFQwaUxDSkJiR3dnUTJoaGJHeGxibWRsY3lJc0lrRnNiQ0JEYUdGc2JHVnVaMlZ6SWl3aVFXeHNJRU5vWVd4c1pXNW5aWE1pWFE9PSJd)
**Screen size**: 2560 x 1440 **Browser size**: 1278 x 955

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by birdofpreyru** [comment]
https://github.com/appirio-tech/react-components/pull/114 (not yet merged) fixes the bug with filter counter, and also fixes wrong rendering of section separator line in the filters sidebar.

I can't fix the wrong position of placeholder in the search bar, as it works fine in Chrome and Firefox on Ubuntu, and I believe you see it in Safari on Mac. Unfortunately, I have no Mac to test and fix it (should be an easy 1-line correction of css though).
