### ISSUE TITLE
feedback - JGHFYUFUYFYFYUF9UFT7D7T5D67RD96DT797R76R67R67

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1052]
**Sender**: None
**Comment**: FGRGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
[Open #2 in Usersnap Dashboard](https://usersnap.com/a/#/topcoder-team/p/topcoder-challen-7ac17f85/2)

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-21/18-59/3e326f36-320b-4c87-8aa2-b1c1ad874548.png'>![feedback - JGHFYUFUYFYFYUF9UFT7D7T5D67RD96DT797R76R67R67](https://usersnappublic.s3.amazonaws.com/2017-02-21/18-59/d1cc23a3-1298-417a-8f85-278a79d2a49c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-21/18-59/3e326f36-320b-4c87-8aa2-b1c1ad874548.png'>Download original image</a>

**Browser**: Safari 9 (OS X El Capitan)
**Referer**: [https://www.topcoder.com/members/Acyn/](https://www.topcoder.com/members/Acyn/)
**Screen size**: 1366 x 768 **Browser size**: 1264 x 616

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by birdofpreyru** [comment]
?
