### ISSUE TITLE
[$20] - User roles in Challenge Details page should be upadted when user registers/unregister

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#1053]
When user registers/unregisters for a challenge pressing corresponding buttons at the Challenge Details page, the user roles loaded in the page controller should be updated properly (re-loaded).
It is expected that the fix should fix the issue with forum link, referenced below.
The issue relates to the code in `tc-site` repo.

**Comment by garntsev** [comment]
When I start topcoder-app application locally and press Compete -> Development challenges (or any other challenges page) I see http://local.topcoder-dev.com:3000/404/ page and then it redirects to https://www.topcoder-dev.com/404/
Please, help me clarify steps required to have challenge page up and running!
Account: christina_uw. Role: user.

**Comment by birdofpreyru** [comment]
This is because current Challenge Details page is served by code from another repo: https://github.com/appirio-tech/tc-site

**Comment by garntsev** [comment]
If Challenge Details page is in the tc-site then shouldn't this bug be in tc-site repo?

**Comment by birdofpreyru** [comment]
@garntsev For the purposes of this Bug Bash we keep the track of all issues in `topcoder-app` repo just to have them in the same place, thus simplifying the management.
