### ISSUE TITLE
[$20] - Update TCO17 Banner in TC Dashboard

### ISSUE THREAD

**Issue by jamesmarquez** [appirio-tech/topcoder-app#1058]
Update the banner of TCO17 in TC Dashboard

The image to be use is https://tco17.topcoder.com/wp-content/uploads/sites/2/2016/08/01b-home-hero.jpg

Then move the content layout to the left just like in the Cognitive banner.

**Comment by ajefts** [comment]
@birdofpreyru Could you put this one on your list  please?

**Comment by birdofpreyru** [comment]
@ajefts Yeap, I've seen it already.
Do you want to start the next Bug Bash already? Or shall we wait for some time, and to queue more staff to do?

**Comment by ajefts** [comment]
how about we open another one and incorporate the new listings issues as
well?  We should coordinate with @tladendo

**Comment by birdofpreyru** [comment]
For the reference, here are the ticket and PR taking care about Cognitive banner: https://github.com/appirio-tech/topcoder-app/issues/1007, https://github.com/appirio-tech/topcoder-app/pull/1014

The new photo for the banner should be nicely cropped! Use your common sense to make the best crop for the target size. It is expected that we have faces and hands of people not cut, while we can their legs partially cut out. Something like this (IT IS JUST A RAPID SAMPLE, I HAVE NOT CHECKED THE TARGET DIMENSIONS AND BEST RESOLUTION WHEN DOING IT - USE ORIGINAL IMAGE TO CROP IT YOURSELF!):

![scr-07](https://cloud.githubusercontent.com/assets/20144632/23832458/ae215e3a-0734-11e7-828c-71b7b0d7cd39.png)

**Comment by shizhouxing** [comment]
@birdofpreyru It's now ready for review.
