### ISSUE TITLE
SM - Final design fixes

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1061]
We have to do several fixes for the existing design to be ready for development:

- [x] Header to reflect challenge title

- [x] Move "back" link under title

- [x] Header to list challenge phase and time remaining (feature update? - may be optional)

- [x] Add link to Online Review (OR) when the accordion is expanded; position at the top of the section

- [x] Add "Help" button at the bottom of the accordion panel, so the user can know how to recover from errors/resolve the issue

- [x] Update InVision prototype (https://invis.io/T98ANQUNH) with the latest designs, remove the pages we don't need.

- [x] Review with Vic

- [x] Deliver final specification as live document (html)

**Comment by Dara-K** [comment]
Hey Vic,

Yes, sure will take care of these.

**Comment by birdofpreyru** [comment]
Is it ready? It looks so by checkboxes above, but I have not got the result yet :)

**Comment by Dara-K** [comment]
No, it's not ready - busy weekend. I didn't know what the checkboxes were for and I checked them when was trying to subscribe on this task before you invited me here. Will work on them tomorrow and check with Vic.

**Comment by Dara-K** [comment]
@vic-topcoder @birdofpreyru Task completed and here are the files - PNGs, HTMLs and the .Sketch source 
https://www.dropbox.com/s/a07c2o4m78vubgr/Submissions%20Management%20-%20FINAL.zip?dl=0

**Comment by vic-topcoder** [comment]
Great! Thanks, @Dara-K

**Comment by vic-topcoder** [comment]
@birdofpreyru I'm making the .svg icons available in "/assets/" here: https://drive.google.com/drive/folders/0B1LbmKnex41fR2pJTkpMaWpTV0k?usp=sharing

`/assets/icons` has the elements from the design; `/assets/fonts/` contains optimized Robot web fonts, `/assets/file-formats/` has the standard set of file type icons we use, to represent the type file attached.

Let's try to use React SVG Loader in this particular project. Get in touch with @mahestro about the scaffolding branch and how we did use it.
