### ISSUE TITLE
Feedback Option is not working.

### ISSUE THREAD

**Issue by harshitmehta123** [appirio-tech/topcoder-app#1067]
Feedback button on the right side of the page is not working.
<img width="1155" alt="screen shot 2017-03-03 at 4 27 07 pm" src="https://cloud.githubusercontent.com/assets/6296738/23548656/87fef5e4-002e-11e7-97da-ef3e214094b8.png">

Says "ERROR -Referrer not valid for this API Key"

**Comment by ajefts** [comment]
fixed
