### ISSUE TITLE
[$30] - Add Unregister button to Dashboard

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#1071]
Add `Unregister` button to active challenge tiles in Dashboard.

Should have the same reddish style, as the `Complete Appeals` button (see https://github.com/Savvas-cl/topcoder-app/commit/ea261e3a15cd00f02263481c690cd140d9c8ac67). Should be visible only for submitters to that challenge, when they have not submitted yet (you can have a look at the logic of similar button in Challenge Details page in `tc-site` repo). Should be present both in Grid and List views of the active challenges in Dashboard.

Also, as this button will be visible together with Submit button, you should ensure that these two buttons have the same width, so that tiles look pretty when these two buttons are shown one under another.

**Comment by shizhouxing** [comment]
@birdofpreyru How can I test this locally? It seems there is nothing in `My challenges`.

**Comment by birdofpreyru** [comment]
You can run it against production backend and just register/unregister from any active challenge

**Comment by shizhouxing** [comment]
@birdofpreyru It's now ready for review.

**Comment by birdofpreyru** [comment]
@shizhouxing Can you update this so that, instead of redirecting to the confirmation page, the button just unregisters the user from the challenge (as it happens on the Challenge Details page), and updates the Dashboard appropriately?

**Comment by shizhouxing** [comment]
@birdofpreyru It seems the logic of buttons at challenge detail page and dashbord are very different. In challenge detail page (in `tc-site` repo) , there are services to do such things, but in the current repo, all buttons on the challenge tile on dashboard page just uses links. The `complete appeal` button also redirects to the Online Review.

**Comment by birdofpreyru** [comment]
Ok, got it. We'll try to handle it in a separate ticket later.
