### ISSUE TITLE
[$15] Filters are not responsive

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1073]

**Comment by birdofpreyru** [comment]
@ajefts @tladendo Seems to be fine now. Should we close this ticket?

**Comment by ajefts** [comment]
Still having some issues with this one...

To reproduce, click Filters when in mobile size and see how the fields are laying out.

![image](https://cloud.githubusercontent.com/assets/3812270/24568698/f0638fc4-1630-11e7-9cc3-2f70e0fb1078.png)
