### ISSUE TITLE
Register call to action seems to be randomly showing or not

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1074]
Sometimes the register call to action is showing, and other times it doesn't.  I can't figure out the logic it's using...but it seems random...

![image](https://cloud.githubusercontent.com/assets/3812270/23723076/c5c6b4da-0415-11e7-8972-35b300575be1.png)

**Comment by ThomasKranitsas** [comment]
Hey guys! I can help here if you want :) The base code was mine I know how the register button works

**Comment by birdofpreyru** [comment]
@tladendo Should I steal this one from you into the Bug Bash?
