### ISSUE TITLE
Remove registration from the challenge timeline tooltip

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1075]
Registration should be a binary option (on/off) on which we establish if a competitor can participate on a challenge or not. It should not be listed as part of the timeline, as it is confusing and overlaps with phases.

![screen shot](https://cloud.githubusercontent.com/assets/8484061/23770881/c46ba3d4-04c9-11e7-88bb-5443352d6ea3.png)

Grouping of active challenges is done based on registration - if I have registered, can I register, or registration is closed. Those are the 3 buckets of active challenges. In that grouping we want to emphasize on how much time is left to register (Call to action) next to the timeline, which shows when the next phase will begin (current phase ends). This is the reason we don't want to list current phase as Registration.

![screen shot 3](https://cloud.githubusercontent.com/assets/8484061/23770972/1ef13f6c-04ca-11e7-86c1-66d729dbb66f.png)
![screen shot 4](https://cloud.githubusercontent.com/assets/8484061/23771020/41f91188-04ca-11e7-8f2b-a38f15b6919e.png)
There can be a case where registration opens before submissions, and that'll be the only case where registration should be listed, but based on the feedback from Tony we never open registration before submission.

**Comment by birdofpreyru** [comment]
@tladendo Should I steal this one from you into the Bug Bash?
