### ISSUE TITLE
[$5] Disable reload when click on active (current) tab navigation

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1077]
![screen shot 11](https://cloud.githubusercontent.com/assets/8484061/23771936/f7e128b6-04cd-11e7-802f-c29228b58c8a.png)
Do not reload the page when clicking on the Challenges tab when it is active. Why do we support reload here?

**Comment by birdofpreyru** [comment]
@tladendo Should I steal this one from you into the Bug Bash?

**Comment by shizhouxing** [comment]
Where are "challenges/SRM" tabs? I can only see a single challenge tab. When I click on it, the page won't reload.

![wx20170402-145943](https://cloud.githubusercontent.com/assets/11014212/24585116/0bae784a-17b5-11e7-87b5-649d8e090ace.png)

**Comment by chq-matteo** [comment]
Can you assign me to this issue? I know how to solve this

**Comment by chq-matteo** [comment]
Can anybody label this as waiting for review? I don't have the permission to do that.

**Comment by chq-matteo** [comment]
Thank you

**Comment by ajefts** [comment]
After review, clicking the Challenges tab is taking the user to the homepage.

**Comment by chq-matteo** [comment]
@ajefts was this issue fixed?

**Comment by ajefts** [comment]
@chq-matteo Yes, this one is done.
