### ISSUE TITLE
[$10] Search button is not active when search is focused

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1078]
![screen shot 12](https://cloud.githubusercontent.com/assets/8484061/23771813/7cb42b2a-04cd-11e7-90d0-7eeed82ba6f3.png)

Should be active (blue) and change states on hover

**Comment by birdofpreyru** [comment]
@tladendo Should I steal this one from you into the Bug Bash?

**Comment by shubhendusaurabh** [comment]
https://github.com/appirio-tech/react-components/pull/169

**Comment by tladendo** [comment]
@vic-topcoder can you review this in dev and confirm that the behavior is correct now?
