### ISSUE TITLE
Forum link icon broken

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1079]
![screen shot 10](https://cloud.githubusercontent.com/assets/8484061/23771860/abe6a49a-04cd-11e7-8db8-34ed1498247f.png)

Expected:
![screen shot 12](https://cloud.githubusercontent.com/assets/8484061/23771874/b8589756-04cd-11e7-89ba-506205b1b6a3.png)

As a move towards the new scaffolding, we should use pure .SVG loaded as react components and styled with CSS. @birdofpreyru is currently working on the react app scaffolding, probably we can come up with a strategy of how to combine the listings with the new repo?

**Comment by birdofpreyru** [comment]
@tladendo Should I steal this one from you into the Bug Bash?
