### ISSUE TITLE
[$10] - Complete Appeals button in Dashboard should be shown only when Submitter role is present

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#1083]
Same for the list view.
![scr-08](https://cloud.githubusercontent.com/assets/20144632/23859777/22a3fd28-0805-11e7-9eec-beefcbe6a8d4.png)

**Comment by WajihaaKanwal** [comment]
Hello,
I am unable to assign this issue to me.

**Comment by birdofpreyru** [comment]
@WajihaaKanwal I've sent you invitation to the repo. The ticket is yours, please assign yourself (I've already changed the label to `IN PROGRESS`).

**Comment by birdofpreyru** [comment]
@WajihaaKanwal Any update on this? Or I will open the ticket for pickup by other people.

**Comment by Savvas-cl** [comment]
@birdofpreyru it is now ready for review
