### ISSUE TITLE
[$10] - Challenge Description text overflowing

### ISSUE THREAD

**Issue by shubhendusaurabh** [appirio-tech/topcoder-app#1091]
If the challenge description contains long text inside `pre` tag, the text is overflowing.

https://www.topcoder.com/challenge-details/30056829/?type=develop
![pre](https://cloud.githubusercontent.com/assets/1818387/24012594/8fb372da-0aa4-11e7-8116-0a7a0843a510.png)

cc @birdofpreyru

**Comment by birdofpreyru** [comment]
Let's, in case of overflow, turn such blocks of unformatted text into scrollable containers. While mantaining original stying as a regular paragraph, when there is no overflow.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Do you want to fix it yourself?
