### ISSUE TITLE
Site design feedback

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1092]
This is from a user that came in via support. A lot of these tutorial pages are on the old design.

> Could I suggest to change text/style formatting on the topcoder.com pages? 
> The font is too small to read it comfortably. And also the font weight is too light (the strokes are thin). And the color of font is grey, not black, or black but too transparent. 
> I really struggle to read the pages on the topcoder. 
> Please, can you pass my feedback to your UI/UX team, it would be wonderful if they improve font format for the reader's eyes. 
> Thank You.

------------------ 
Submitted from: https://www.topcoder.com/community/data-science/data-science-tutorials/binary-search/

**Comment by ajefts** [comment]
@vic-topcoder fyi...

**Comment by vic-topcoder** [comment]
We're going to address this in the challenges on the platform project. It should be quick, and fixes on the current page are going to be discarded when the new pages arrive. This is a known issue and we will improve the typography with the next release on challenge pages
