### ISSUE TITLE
[$20] - Add TCO link to the top nav in tc-site like it is on topcoder-app

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1093]

**Comment by birdofpreyru** [comment]
This is the link in the top menu in desktop view:
![scr-11](https://cloud.githubusercontent.com/assets/20144632/24044993/e56b8fcc-0b1d-11e7-8055-cd1c81bc4f37.png)
there is similar link in mobile-size view.

Both are missing on Challenge Details page (and on other pages served from `tc-site` repo) and should be added there.

**Comment by Savvas-cl** [comment]
@birdofpreyru it is now ready for review.
