### ISSUE TITLE
Status labels text

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1102]
Let's provide an adequate content to users. When we have 

- **Stalled**: `NaN:NaN h to go` → "Challenge is currently on hold"
- When we have `00 d 00:23 h to go` - drop the 00d; if we have days and min, display that, if we have only min, display minutes:
  - `00 d 06:46 h to go ` → `6:46 h to go'
  - `00 d 00:46 h to go ` → `46 min to go'
- **Final Fixes** → "Winner is working on fixes"
- **Late** : say by how much it is late `Late by 34 min`, `Late by 4:53 h`, `Late by 2 d 23:45 h`
![pasted_image_at_2017_03_28_09_45_am_360](https://cloud.githubusercontent.com/assets/8484061/24425203/282b2cf8-13b8-11e7-9d6e-b18a3383fb49.png)
![pasted_image_at_2017_03_28_09_46_am_360](https://cloud.githubusercontent.com/assets/8484061/24425204/283b574a-13b8-11e7-9b69-fabbb6588b40.png)

@ajefts Please chime in if I missed any status that is not directly translated to time period

**Comment by ajefts** [comment]
@ThomasKranitsas Want to do this one quick too?

**Comment by tladendo** [comment]
fixed
