### ISSUE TITLE
New Listings - registration phase show as open when it's not

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1103]
On the new listings, you'll see challenges showing in the "Open for registration" list that are Completed challenges.  I believe this is because the page is looking at the phase dates, and not the status. Especially for F2F, it's very likely to see the registration end date in the future even when the phase/challenge is closed.

**Comment by ajefts** [comment]
@tladendo Let's get this one fixed asap please.

**Comment by ThomasKranitsas** [comment]
@ajefts @tladendo I've fixed this before but it seems that a change made later broke my code 🤔

**Comment by ajefts** [comment]
@ThomasKranitsas can you fix it again?

**Comment by ThomasKranitsas** [comment]
@ajefts it's a quick one so yep.. Just give me few minutes.

**Comment by ThomasKranitsas** [comment]
@ajefts just to confirm... That issue only appears when you select the `All Challenges` option from the sidebar filters, right?

**Comment by ajefts** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30057023/?type=develop&noncache=true
