### ISSUE TITLE
New Listing - prize tooltip and challenge link has hard coded api path

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1105]
Looks like it's always hitting the prod domain

**Comment by birdofpreyru** [comment]
I've checked the commit ff79d46087ca07c424fe9ee806fc45e8964a64c4 in this repo, and it looks to me like `/listings` there already use the correct backends for dev and prod modes.

**Comment by ajefts** [comment]
Hi @birdofpreyru 

It's actually the URL that it's using when you click a challenge and also when it calls the API to get prizes.  In dev, it's using www.topcoder.com instead of www.topcoder-dev.com....

**Comment by birdofpreyru** [comment]
Ok, this should fix it: https://github.com/appirio-tech/react-components/pull/147

**Comment by tladendo** [comment]
confirmed that this fix works
