### ISSUE TITLE
[$15] - New Listings - Clicking My Challenges in sidebar doesn't work

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1107]

**Comment by daft300punk** [comment]
Please assign me this, topcoder handle: daft300punk. Have figured out the problem, will send PR soon.

**Comment by ajefts** [comment]
@daft300punk I've updated your permissions.  Please submit your fix as soon as you can.  Thanks!

**Comment by daft300punk** [comment]
here - https://github.com/appirio-tech/react-components/pull/179

**Comment by daft300punk** [comment]
here - https://github.com/appirio-tech/react-components/pull/180
