### ISSUE TITLE
New Listings - Register link is not set

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1108]
![image](https://cloud.githubusercontent.com/assets/3812270/24478285/51be6256-14a8-11e7-9b06-59ec86bb8dbe.png)

The "to register" action needs to go to the challenge page.  Use the same url that the challenge name is using.

**Comment by ThomasKranitsas** [comment]
@ajefts I'm not sure if that was fixed but on the very first challenge I had set the register button to be randomly appeared on some challenges regardless if they are open for registration or not.

The reason was to mock the scenario that the button appears to challenges that a user hasn't been registered yet.

I guess the fix for this should be to either show the register button if the challenge is open for registration.

And if it's necessary and we can fetch the user's challenges we can hide that button on the challenges that user is already registered.

**Comment by ajefts** [comment]
Ok, after talking with @vic-topcoder let's add some more detail to this. Please refer to the specs here:  https://drive.google.com/open?id=0B1LbmKnex41fRWNNdXNTQzdDNzA

For the timeline, we should assume the registration "phase" does not exist.  So, if registration is open the there should be the call to action to the right ("....to register") and that should show the time left to register.  When registration is closed, that call to action goes away.  On the timeline tooltip, we should not show Registration as a phase.  So, when the pulling the phases for the challenge, ignore registration as an open phase when generating the timeline.  The time left underneath the timeline should refer to the time left in the current phase (Not registration phase).

**Comment by ThomasKranitsas** [comment]
@ajefts currently it's not only the register button which is randomly shown... It's also the forum link icon.. Should I leave the code which randomly shows the forum icon and just show the register button for all challenges that are open for registration?

**Comment by vic-topcoder** [comment]
@ThomasKranitsas we don't want any random generations of the interface anymore. We should follow only the functional logic as we're pushing to get this into production. Let's have all challenges sorted in the correct buckets. 
 - Treat "open for registration" as a boolean to show the register button, and remove it as a phase on the timeline. Registration should not be shown as a current phase name as well.
- Forum link should be shown only on challenges that the user is registered to, not all challenges. The goal in the next iterations is to allow members to quickly identify when there are new discussions/messages in the forums in challenges they're registered for. For all the other challenges, we don't want to show the forum link, as that is overwhelming data.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder I've already removed the random bool here https://github.com/appirio-tech/react-components/pull/148

About the forum link: How am I supposed to implement this on the `react-components` to show the forum link only to challenges where a user is registered?

**Comment by ajefts** [comment]
@ThomasKranitsas Can we check the "my challenges" list for the user and show the forum icon based on that?

**Comment by ajefts** [comment]
@ThomasKranitsas It looks like the tooltip for the timeline is always hitting the prod API.  Can you update this some the url is configured based on the env?  I think @birdofpreyru just did this for a few other components.
