### ISSUE TITLE
[$20] - Side navigation doesn't reflect current bucket/list

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1110]
When clicking on "load more" at the end of a bucket, the side navigation doesn't reflect the selection. It should navigate to the appropriate section. Clicking on "load more" should function the same as clicking on the side navigation.

![screen shot 54](https://cloud.githubusercontent.com/assets/8484061/24488508/2d61d2c0-14cc-11e7-8740-cd2893e8ab27.png)

**Comment by tladendo** [comment]
working on some related filter issues, will look at this after they wrap up

**Comment by chq-matteo** [comment]
Can I be assigned to this issue please?

**Comment by tladendo** [comment]
@chq-matteo i'm assuming this one was ready for review, since your PR worked

**Comment by chq-matteo** [comment]
@tladendo Yeah sorry I don't have the permission to change labels.
