### ISSUE TITLE
Side navigation is not sticky

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1111]
After the latest updates the side navigation doesn't stick anymore to the top of the viewport on scroll. It should stick.
![screen shot 55](https://cloud.githubusercontent.com/assets/8484061/24488546/577cdeba-14cc-11e7-8cd3-5424e78ad764.png)

**Comment by vic-topcoder** [comment]
We also lost the RSS feed link under the navigation; can we get it back @tladendo ?

**Comment by tladendo** [comment]
@ThomasKranitsas this is already fixed now
