### ISSUE TITLE
[$10] Layout issues - prize disappearing on resize

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1113]
Current implementation of mobile view hides the prize on the challenge card. It should be brought back.

Expected:
![screen shot](https://cloud.githubusercontent.com/assets/8484061/24525793/94ba89c4-1550-11e7-9e17-595a83d8d5bc.png)

Current:
![screen shot 2](https://cloud.githubusercontent.com/assets/8484061/24525800/98f21e26-1550-11e7-8eeb-9b727d79d45b.png)
![screen shot 1](https://cloud.githubusercontent.com/assets/8484061/24525802/9a8f758a-1550-11e7-9ebc-01effef9f40e.png)

**Comment by vic-topcoder** [comment]
It happens on "open for registration" only challenges

**Comment by tladendo** [comment]
got someone looking into this

**Comment by tladendo** [comment]
@ajefts don't add this to the bug bash, i have a patch already. Just waiting for a conflict resolve
