### ISSUE TITLE
[$20] - New Listing - past challenges are ordering wrong

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1115]
it also shows all MM challenges first.  This should be sorted desc...

**Comment by tladendo** [comment]
@ajefts not sure i understand, can you provide more details?

**Comment by ajefts** [comment]
Please load the app in a clean browser and click past challenges in the side bar.  This is what you will get:

![image](https://cloud.githubusercontent.com/assets/3812270/24567482/f27263bc-162b-11e7-9724-298ec4163b9e.png)

**Comment by tladendo** [comment]
@ajefts sorted descending on what basis?

**Comment by ajefts** [comment]
Most recently completed challenges should be at the top.

**Comment by tladendo** [comment]
@shizhouxing You've marked many issues "READY FOR REVIEW" but I don't see any PRs from you. What's going on? If you're not working on the issues, please set them to "OPEN FOR PICKUP"

**Comment by shizhouxing** [comment]
@tladendo My PRs are at react-components repo.
