### ISSUE TITLE
[$10] - Listing bucket footer is wrong

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1118]
The current listing footer is not up to speck:

Current:
![screen shot 4](https://cloud.githubusercontent.com/assets/8484061/24531255/7f314a4a-156c-11e7-9b45-f1299be61b97.png)

Expected:
![screen shot 6](https://cloud.githubusercontent.com/assets/8484061/24531257/841727c8-156c-11e7-8add-2d891c56830d.png)

**Comment by tladendo** [comment]
I have someone looking at this

**Comment by tladendo** [comment]
submitter is focusing on another issue -- added to bb
