### ISSUE TITLE
[$50] - Side menu and list title updates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1119]
We need to split active challenges from past challenges. This can be done with a slight update on the side menu, and title of the buckets. The listing should still include the recently finished challenges as a nice segue to explore past challenges. All active is the combined list view, so the count should include the total number of all sub-groups (Participating, Open for registration, Running).

**Changes:**
- Split active from past challenges
- Increase distance between challenges and filters
- Move the RSS link at the end of the menu;
- Add the footer as long pages won't allow the users to reach the footer easily;
- Rename the buckets according to the spec.

Live speck: https://drive.google.com/drive/folders/0B1LbmKnex41feTd4S1YzODJvR2c?usp=sharing

![pages-challenges---menu-update](https://cloud.githubusercontent.com/assets/8484061/24533447/a3a464f6-157c-11e7-8758-d5d767b636de.png)

**Comment by vic-topcoder** [comment]
@ajefts Tony, please advise if any changes of the labels are necessary.

**Comment by tladendo** [comment]
@ThomasKranitsas are you taking a look or should i pull someone else in?

**Comment by ThomasKranitsas** [comment]
@tladendo I'm afraid I won't be able to do this today. If you have someone available to do this today please assign it to him/her

**Comment by shizhouxing** [comment]
Some questions:

"Split active from past challenges"
Isn't it already splited?

"Add the footer as long pages won't allow the users to reach the footer easily;"
Sticky footer?

**Comment by tladendo** [comment]
It's not already split. They need to be separate columns in the sidebar.

@vic-topcoder what's the thing about the footer?

**Comment by shizhouxing** [comment]
@tladendo @vic-topcoder  There is no footer in spec, but there is already one in the current code.

**Comment by shizhouxing** [comment]
@vic-topcoder 

"Increase distance between challenges and filters"

What distance were you referring to? I can't see the difference between current code and spec. Could you please point it out in the image? Thank you.

**Comment by vic-topcoder** [comment]
@shizhouxing - the footer under the side navigation is the one available in code. The reason is that with a very long list people might not be able to scroll to the current footer of the page. The RSS link in the current code must be brought back into the side navigation, as it is connected to the challenges, not generic RSS feed.

**Comment by ajefts** [comment]
Hi guys,

Is there more info we need for this one?

I think we're functionally close to what we need, but we need to design updates.  

@vic-topcoder I'm not crazy about the updated naming.  I'd leave it as is for now :)
