### ISSUE TITLE
[$20] - New Listing - subtrack not showing all tracks

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1121]
![image](https://cloud.githubusercontent.com/assets/3812270/24567159/7cbe0ca8-162a-11e7-9f3d-9e8f2a21c8a0.png)

Where are the subtracks/challenge types getting pulled from?  This is not the full list.  The full set of subtracks should come from:

https://api.topcoder.com/v2/develop/challengetypes
https://api.topcoder.com/v2/design/challengetypes

**Comment by tladendo** [comment]
should we use the API or hardcode this?

**Comment by ajefts** [comment]
API

**Comment by tladendo** [comment]
@shizhouxing Left comment in PR about environments

**Comment by shizhouxing** [comment]
@tladendo Updated.
