### ISSUE TITLE
[$10] New Listing - Open for Review changes

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1124]
On the "All Challenges" view, hide the "Open for Review" section.

Also, in the sidebar please change the behavior of the "Open for review" link so it loads https://www.topcoder.com/review/development-review-opportunities/.

![image](https://cloud.githubusercontent.com/assets/3812270/24578866/3cba22c0-16b8-11e7-9957-b91dcb18bf33.png)

**Comment by tladendo** [comment]
@shizhouxing see comment on PR

**Comment by shizhouxing** [comment]
@tladendo updated.
