### ISSUE TITLE
[$5] New Listings - Clicking My Challenges not working

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1126]
When you click My Challenges in the sidebar, it is not loading anything.  It should be loading the My Challenges view for the challenges that I'm participating in.

![image](https://cloud.githubusercontent.com/assets/3812270/24579006/073a1c6a-16bb-11e7-85a0-c434aa3ba6da.png)

**Comment by shizhouxing** [comment]
It seems this issue is the same as #1107.

**Comment by daft300punk** [comment]
Is this solved? If not, can you assign me this?

**Comment by shizhouxing** [comment]
@daft300punk Sorry it seems I don't have permission to do this.

**Comment by daft300punk** [comment]
@ajefts Can you give me permission to collaborate?
