### ISSUE TITLE
[$5] New Listing - RSS link not set

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1128]
The "Get the RSS" link in the sidebar footer should be opening https://feeds.topcoder.com/challenges/feed?list=active

![image](https://cloud.githubusercontent.com/assets/3812270/24579039/805f7e64-16bb-11e7-9f64-1ae800c2ff24.png)

**Comment by k-tempest** [comment]
Can I work on this one? I don't have permission to assign myself.

**Comment by tladendo** [comment]
@k-tempest I couldn't add you right now, but I assigned myself in your place (I'm the copilot). Please start working on it and we'll get you in the system as soon as we can.

**Comment by ajefts** [comment]
@k-tempest I invited  you, so you should be able to assign yourself now.  Thanks.

**Comment by k-tempest** [comment]
@tladendo @ajefts thank you.
Unfortunately, I still cannot assign myself although I'm in the competitors group

**Comment by ajefts** [comment]
ok, I assigned you.  I think I fixed the perms too so you can assign yourself going forward.  Thanks!

**Comment by Gauravseta** [comment]
Can i participate in this challenges?
