### ISSUE TITLE
[$10] New Listings - All Challenges count

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1130]
Exclude the past challenges count from the All Challenges count.  

The All Challenges count should be equal to the sum of "Open for  Registration" + "Ongoing challenges".

![image](https://cloud.githubusercontent.com/assets/3812270/24579171/04531f6c-16be-11e7-8d95-e99ff7aadf01.png)

**Comment by shizhouxing** [comment]
@tladendo How to load the listing page? I can't see any challenges at local.topcoder-dev.com:3000/listings. Thank you.
