### ISSUE TITLE
Layout rendering performance issues

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1133]
Current rendering on challenge listings is not optimized. Initial load, clicking on side navigation, reordering  - all have a significant delay (2-4s). This is caused by layout trashing, heavy calculations and scripting. We need to update the components used to not cause recalculating. The initial research on performance in chrome dev tools timeline shows a lot of the problems happen with recalculating the components. We need to eliminate that.
![pasted_image_at_2017_03_31_10_36_am](https://cloud.githubusercontent.com/assets/8484061/24582126/d1e00fc0-16dd-11e7-943e-7764624ab4f8.png)
![pasted_image_at_2017_03_31_03_49_pm](https://cloud.githubusercontent.com/assets/8484061/24582127/d37cb1f8-16dd-11e7-954a-e1e03d01694a.png)

https://medium.com/dailyjs/react-is-slow-react-is-fast-optimizing-react-apps-in-practice-394176a11fba and https://blog.vixlet.com/react-at-light-speed-78cd172a6411. https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#profiling-components-with-chrome-timeline can help

**Comment by vic-topcoder** [comment]
All, I think your expert knowledge can help in this case - that's why I add you all to the ticket. Any suggestions on how to better do the stack and optimize the rendering would be great. I saw something like recalculating the absolute position of each tooltip for each card, which was crazy! We should really optimize the rendering, as this would destroy the user experience on the page. I cannot imagine we release the update to the public before we nail the speed of this page. React is great with updates of elements when needed, so we're doing something very wrong here.

**Comment by tladendo** [comment]
@vic-topcoder Can we pick a few really specific things to optimize? I messed a little bit with the timeline stuff but I'm still not sure I really know what I'm looking for. Maybe the timeline tooltips? And are you seeing the same problem with the sidebar?

**Comment by vic-topcoder** [comment]
The quickest way to test is to disable the tooltip. Currently, the tooltip recalculates sizes even when it is invisible, which amounts to those loading problems. Can we try with a different tooltip component, as the one we currently use probably won't be easy to change.

**Comment by vic-topcoder** [comment]
![pasted_image_at_2017_04_04_12_33_pm](https://cloud.githubusercontent.com/assets/8484061/24675279/6296f0d6-1933-11e7-9ec3-4563716cada7.png)
We should disable the calculation of all tooltip instances unless the user hovers on a trigger, and then calculate. This calculation on a large scale is what kills the performance.

**Comment by ajefts** [comment]
Going to close this since a lot of updates and refactoring have take place.  We can open up new issues as needed for performance.
