### ISSUE TITLE
[$5] New Listings - remove counts from My Filters

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1136]
Remove the counts from the My Filters section.  It's not calculating the count until you click on them, so let's just remove the counts to avoid confusion.

![image](https://cloud.githubusercontent.com/assets/3812270/24621312/035c3da2-186f-11e7-93cb-f0cb38f08704.png)

**Comment by shizhouxing** [comment]
PR merged: https://github.com/appirio-tech/react-components/pull/181
