### ISSUE TITLE
[$15] New Listings - prize overlap on smaller screens

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1138]
Please see this screenshot:  
![image](https://cloud.githubusercontent.com/assets/3812270/24626716/32dd23c8-1880-11e7-9227-8e3ea851a07a.png)

Notice as you shrink the browser size the prize overlaps the other elements.

**Comment by Gauravseta** [comment]
Can you please assign this to me?

**Comment by Gauravseta** [comment]
How to self assign? I am not able to see any such link or button.

**Comment by Gauravseta** [comment]
Please dont assign it to me..I wont be able to complete.

**Comment by tladendo** [comment]
@shizhouxing your fix moves prize to far to the left for mobile view. compare with the current styling.

**Comment by shizhouxing** [comment]
@tladendo Updated.
