### ISSUE TITLE
[$15] New Listings - All Challenges getting added as a filter item

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1140]
For some reason, "All Challenges" is listed in My Filters.  However, I don't have a filter with that name.  It's causing issues especially when you link directly to a page that is filtered like this:

https://www.topcoder.com/listings/#&tracks=design&mode=6&name=All%20Challenges

Instead of loading the standard page filtered on Design challenges only, it loads the "All Challenges" filter view...which I'm not sure what it is pulling...

Please remove All Challenges as a My Filter.

![image](https://cloud.githubusercontent.com/assets/3812270/24631227/902b9db8-188d-11e7-9fe5-aba04bf51cb9.png)

**Comment by Gauravseta** [comment]
@ajefts Request you help me. How can i get acess to assign myself if i wish to solve an issue.

**Comment by Gauravseta** [comment]
@ajefts Sir please guide.Cant i receive any issue to solve?

**Comment by ajefts** [comment]
Hi @Gauravseta.  I've invited you to the team so you can work on these.  Thanks!

**Comment by Gauravseta** [comment]
@ajefts I am still not able to assign issue to myself..Please help..
