### ISSUE TITLE
[$5] Hide "Feedback" widget

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/topcoder-app#1141]
Let's remove the Usersnap feedback widget. We had it only for the Alpha version, so in prep for production we don't need it anymore.

![screen shot 2](https://cloud.githubusercontent.com/assets/8484061/24632721/18520934-187a-11e7-9183-fa2a9a7a434f.png)

**Comment by Gauravseta** [comment]
@vic-topcoder request you to provide self assigning rights.I do wish to solve issue.

**Comment by ajefts** [comment]
@Gauravseta You should be able to assign yourself now, right?
