### ISSUE TITLE
[$5] - New Listings - Sidebar should be level with challenge listings

### ISSUE THREAD

**Issue by tladendo** [appirio-tech/topcoder-app#1142]
Some new changes knocked the alignment of these two off.

**Comment by Gauravseta** [comment]
@tladendo I am not able to assign this issue to myself..Please invite me to team..Thanks..Please reply

**Comment by Gauravseta** [comment]
@tladendo I found the link to accept the invitation which was sent by @ajefts .Thanks @ajefts
