### ISSUE TITLE
[$5] New Listings - set register link

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1151]
The Register  button at the end of the challenge card should take the user to the challenge details.  Same link that the challenge title uses.

![image](https://cloud.githubusercontent.com/assets/3812270/24712882/1ab0587e-19f2-11e7-9c6f-44f3a109a5c8.png)

**Comment by chq-matteo** [comment]
Can you assign me this issue please?Can you assign me this issue please?

**Comment by ajefts** [comment]
@chq-matteo I sent you a team invite.  Please accept and then you should be able to assign it.

**Comment by chq-matteo** [comment]
Thanks
