### ISSUE TITLE
Active challenge listed as stalled challenge

### ISSUE THREAD

**Issue by sharathkumaranbu** [appirio-tech/topcoder-app#1153]
There is an active challenge which is listed as stalled challenge in new listings page.

Please find below.

Actual Challenge page:

![image](https://cloud.githubusercontent.com/assets/7723558/24717305/9efbc8cc-1a4f-11e7-85a3-5d7bdcb4b167.png)

Topcoder listing page:

![image](https://cloud.githubusercontent.com/assets/7723558/24717334/b92bb946-1a4f-11e7-9188-d5909a63258e.png)

**Comment by ajefts** [comment]
Hi @sharathkumaranbu 

Can you show me your url and sidebar?  II'm not seeing the same as you, but it could be a filtering bug.

Thanks.

![image](https://cloud.githubusercontent.com/assets/3812270/24720229/53eb75de-1a0a-11e7-9f4d-c2ac70c7cb57.png)

**Comment by sharathkumaranbu** [comment]
Now when I check it, it's fine. I don't know what happened.

Initially I clicked on My Challenges, as you see on the ticket.
