### ISSUE TITLE
[$50] - New Listings - Add section for Upcoming Challenges

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1154]
Add a section that is just like Ongoing challenges, except it will be labeled "Upcoming challenges" and will retrieve upcoming challenges from the API.

Put this section at the end after Open for Review.

**Comment by ajefts** [comment]
fyi @tladendo I updated the description

**Comment by tladendo** [comment]
The "upcoming" endpoint looks like this: http://api.topcoder.com/v2/challenges/upcoming?type=develop

For more details, see the [Apiary doc](http://docs.tcapi.apiary.io/#reference/software-challenges/search-upcoming-software-challenges/search-upcoming-software-challenges).
