### ISSUE TITLE
[$5] New Listings - sidebar footer links

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1155]
Please add the proper url targets for the footer links in the sidebar.  They should match the footer URLs you see on https://www.topcoder-dev.com/my-dashboard.  Also, remove the "More" item.

![image](https://cloud.githubusercontent.com/assets/3812270/24726417/5022a9a2-1a20-11e7-80da-55bd31c2e5a1.png)

**Comment by tladendo** [comment]
bug bash 2
