### ISSUE TITLE
[$30] New Listing - Active Marathon matches are not showing

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1163]
There are 2 active matches in prod that aren't showing on the new listings page.  I believe this was broken in a recent update.  

I can see the API calls in the console returning the 2 marathon matches.  I can also see that the past marathon matches are displaying.  So, I believe it's an issue with the front end logic.

**Comment by ajefts** [comment]
@shubhendusaurabh @ThomasKranitsas @birdofpreyru @shizhouxing @Colinh84 @chq-matteo Looking for a quick fix on this one if you can....

Also for this one:  https://github.com/appirio-tech/topcoder-app/issues/1164

**Comment by shubhendusaurabh** [comment]
@ajefts in which list these marathon matches should show up? "Open for registration" or "Ongoing challenges"?

**Comment by ajefts** [comment]
if you look in the console, you can see them getting returned in the api calls...

https://api.topcoder.com/v2/data/marathon/challenges/?listType=active

**Comment by chq-matteo** [comment]
@ajefts @appirio-jenkins I think I know the solution, how many challenges are you registered in? It would also solve the other open issue #1164

**Comment by shubhendusaurabh** [comment]
appirio-tech/react-components/pull/207

**Comment by ajefts** [comment]
@shubhendusaurabh Thanks for the fix.  It looks to be working.

Since this was outside the timeline of the official bug bash, I can't count it towards that but you'll definitely still get the payment for this one directly.

**Comment by ajefts** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30057145/?type=develop&noncache=true
