### ISSUE TITLE
[$30] - New Listing - clean up constants

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1167]
I've noticed quite a few cases of using hardcoded constants for things like api urls.  These need to all be part of config and able to be different for dev/qa/prod environments.

For example, right now, a search of the /components folder in react-components returns about 20 results. All of these should be determined dynamically, using props like MAIN_URL.

**Comment by ajefts** [comment]
@tladendo This might be good for a short cleanup code challenge.  Let's do it soon as I know want it to propagate for too long...

**Comment by tladendo** [comment]
@tonyj how about launching another bug bash for cleanup? that way i can just make tasks for all the little outstanding things while also cleaning up other remaining issues

**Comment by shubhendusaurabh** [comment]
appirio-tech/react-components/pull/213 and appirio-tech/webpack-config/pull/34
