### ISSUE TITLE
[$30] - New Listings - Navigation within listings page

### ISSUE THREAD

**Issue by tladendo** [appirio-tech/topcoder-app#1168]
If you're on the /challenges page, and use the top navigation (Compete > Design, etc.), the URL hash will update, but the page won't update. Ideally, the listings component should update without a page reload.

**Comment by chq-matteo** [comment]
Notice that both pull requests are needed for this fix to work.

**Comment by chq-matteo** [comment]
I think that these patch will fix also #1161
