### ISSUE TITLE
[$15] - New Listings - filter and search glitch

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1169]
Sky_ reported this issue. Users who do a search and then navigate to the "Open for registration" tab will encounter a glitch with the infinite listings.

  Please see the video...

http://take.ms/gtuqh

**Comment by ajefts** [comment]
fyi @tladendo

**Comment by mk7293** [comment]
@tladendo, @ajefts - pls grant the access.

**Comment by mohhasbias** [comment]
may I change the assignee?

**Comment by mohhasbias** [comment]
the label is ```OPEN FOR PICKUP``` but the assignee is not released yet.

**Comment by tladendo** [comment]
@mohhasbias @mk7293 the assignee is released

**Comment by mk7293** [comment]
@tladendo, @ajefts Still, I think I dont have permission. I cant able to add me in the assignees.

**Comment by ajefts** [comment]
Hi @mk7293 I sent you an invite for access.  Welcome to the Bug Bash :)

**Comment by tladendo** [comment]
@mk7293 self-assignment is for 24 hours. Please wrap up the ticket or unassign yourself
