### ISSUE TITLE
[$15] - New Listings - Should be able to expand keyword lists

### ISSUE THREAD

**Issue by tladendo** [appirio-tech/topcoder-app#1171]
Long keyword lists will have a little number indicated the amount of extra keywords that can't be shown (e.g., "+5"). This should be expandable. Right now it isn't.

**Comment by bkavita** [comment]
Not able to assign the bug. Please grant the access.

**Comment by mohhasbias** [comment]
how to assign the bug?

**Comment by chq-matteo** [comment]
click on the gear icon near 'Assignees'

**Comment by mohhasbias** [comment]
there is no gear.
![image](https://cloud.githubusercontent.com/assets/2347137/24829549/1d6e5170-1c9e-11e7-886f-b4f6c80825ef.png)

maybe i miss something...

**Comment by chq-matteo** [comment]
Ah you are not in this repository team yet, I don't know if @bkavita is still looking for a fix

**Comment by bkavita** [comment]
Yes I am still waiting for someone to grant me access :)

**Comment by bkavita** [comment]
@tladendo, @ajefts - pls grant the access.

**Comment by chq-matteo** [comment]
@bkavita if you think you can solve this in 24h I'll label this issue as 'In progress', when you are done submit a pull request linking this issue and I'll label it as 'waiting for approval'

**Comment by ajefts** [comment]
@bkavita and @mohhasbias I sent you both an invite.  Thanks!

**Comment by mohhasbias** [comment]
@ajefts thank you for the invite

**Comment by Gauravseta** [comment]
@tladendo ..I know wherechanges are to be done.I just need some more time.

**Comment by tladendo** [comment]
@Gauravseta if no one else assigns you can pick it up again
