### ISSUE TITLE
Unable to build locally.

### ISSUE THREAD

**Issue by Gauravseta** [appirio-tech/topcoder-app#1172]
Constantly I am getting below error while running commands as mentioned in Readme.
Note : npm and node versions are correct.
below is data from log file

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle topcoder-app@~prebuild: topcoder-app@
6 silly lifecycle topcoder-app@~prebuild: no script for prebuild, continuing
7 info lifecycle topcoder-app@~build: topcoder-app@
8 verbose lifecycle topcoder-app@~build: unsafe-perm in lifecycle true
9 verbose lifecycle topcoder-app@~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\HP-LP\topcoder-app-dev\topcoder-app-dev\node_modules\.bin;C:\Program Files\nodejs;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\PHP\v5.6;C:\Program Files\PHP\v5.3;C:\Program Files (x86)\Intel\iCLS Client\;;C:\PrServer\130\Tools\Binn\ManagementStudio\;C:\ProgramData\chocolatey\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Program Files\nodejs\;C:\Users\Jason\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\Jason\AppData\Roaming\npm
10 verbose lifecycle topcoder-app@~build: CWD: E:\HP-LP\topcoder-app-dev\topcoder-app-dev
11 silly lifecycle topcoder-app@~build: Args: [ '/d /s /c', 'webpack --bail --progress --build --tc' ]
12 silly lifecycle topcoder-app@~build: Returned: code: 1  signal: null
13 info lifecycle topcoder-app@~build: Failed to exec build script
14 verbose stack Error: topcoder-app@ build: `webpack --bail --progress --build --tc`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid topcoder-app@
16 verbose cwd E:\HP-LP\topcoder-app-dev\topcoder-app-dev
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v5.9.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error topcoder-app@ build: `webpack --bail --progress --build --tc`
22 error Exit status 1
23 error Failed at the topcoder-app@ build script 'webpack --bail --progress --build --tc'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the topcoder-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --bail --progress --build --tc
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs topcoder-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls topcoder-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by chq-matteo** [comment]
try with an ubuntu-based os

**Comment by tladendo** [comment]
question: does react-components build for you?

**Comment by Gauravseta** [comment]
react components are visible in my directory "node_modules".

**Comment by tladendo** [comment]
many of the issues can be fixed using just the react-components repo. only a couple need topcoder-app.

are you using nvm for your node version?
