### ISSUE TITLE
Remove items from Compete header

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1179]
Remove the sub items from the Compete top nav and make it so clicking "Compete" takes you to the /challenges page.  Let's make sure this still remains mobile friendly.

**Comment by ajefts** [comment]
@birdofpreyru want to do a F2F for this one?

**Comment by birdofpreyru** [comment]
@ajefts: Yeap, I can take care about it.
A question though: what about the `Competitive Programming` item in `Compete` sub-menu (takes to `arena.topcoder.com`)? Should we leave the sub-menu, and just replace four other items (`All Challenges`, `Design Challenges`, `Development Challenges`, `Data Science Challenges`) by a single item, say `Active Challenges`?

**Comment by Gauravseta** [comment]
No money? No labels for this?

**Comment by birdofpreyru** [comment]
@Gauravseta I'll open a dedicated F2F challenge as soon as @ajefts confirms the details.

**Comment by ajefts** [comment]
The original idea was to use the /challenges page for nav to all the different tracks, including competitive programming.  We have the SRM tab on there that takes you to arena.topcoder.com and eventually will populate the page with SRMs.

However, I can see now that it's probably not obvious to users and people that don't know what SRM is would be lost.  So, let's keep your idea for now.  All Challenges + Competitive Programming.


![image](https://cloud.githubusercontent.com/assets/3812270/25279103/70a998ca-2673-11e7-8195-dc6283fc4f37.png)

**Comment by birdofpreyru** [comment]
UPDATE: F2F is scheduled and will go live soon: https://www.topcoder.com/challenge-details/30057344/?type=develop&noncache=true

**Comment by birdofpreyru** [comment]
@ajefts Fixed in these commits:
https://github.com/appirio-tech/tc-site/commit/ae028c249ec507e52a47893f3a746d7c69ba23df
https://github.com/appirio-tech/topcoder-app/commit/9ca6d965a3c28f58c8b195617356f567c341ca62
Though, not fixed in legacy parts of the site, like forum App, may be somewhere else.
