### ISSUE TITLE
Marathon links for registrants and submitters wrong on past challenges.

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1180]
On https://www.topcoder.com/challenges/#&tracks=datasci&mode=6&name=Past%20challenges, if you look at the links for the registrants and submissions on the "MM" challenges, they are wrong.  They need to go to links like this:

Registrants:  https://community.topcoder.com/longcontest/?module=ViewRegistrants&rd=16903
Submissions:  https://community.topcoder.com/longcontest/?module=ViewStandings&rd=16903

Replace rd with the round Id

![image](https://cloud.githubusercontent.com/assets/3812270/25279261/e9404d06-2673-11e7-93ad-9a23e60c0f93.png)

**Comment by ajefts** [comment]
@birdofpreyru Here is another easy one.

**Comment by birdofpreyru** [comment]
UPDATE: F2F is scheduled and will go live soon: https://www.topcoder.com/challenge-details/30057344/?type=develop&noncache=true

**Comment by birdofpreyru** [comment]
@ajefts Fixed in https://github.com/appirio-tech/react-components/commit/e41dccd41d890c96cbdce0c2c10aab03e6dd5940
Should be pushed to prod, and we can close the ticket.
