### ISSUE TITLE
Add cognitive to signup skill picker page

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1183]
Add the option for Cognitive to the skill picker page when registering (https://www.topcoder.com/skill-picker).  This should behave the same way that Predix does in terms of integrating with mailchimp and our member cert service.

**Comment by ajefts** [comment]
@vikasrohit Do you think you could do this one this week?

**Comment by vikasrohit** [comment]
@ajefts do you have the program/event id ready?

**Comment by vikasrohit** [comment]
I just recalled, we already have the Cognitive in skill picker. 😬
