### ISSUE TITLE
MOBILE https://www.topcoder.com/community/members/

### ISSUE THREAD

**Issue by vbaileytopcoder** [appirio-tech/topcoder-app#1212]
Mike Morris mentioned today that he views https://www.topcoder.com/community/members/ quite frequently and it does not render on mobile.

**Comment by ajefts** [comment]
@birdofpreyru This is not urgent, but maybe run a small challenge to clean this up when you get a chance...

**Comment by birdofpreyru** [comment]
@ajefts The F2F challenge is prepared & scheduled: https://www.topcoder.com/challenge-details/30058022/?type=develop&noncache=true

**Comment by birdofpreyru** [comment]
@ajefts The fix is ready and deployed to `dev`. I don't risk to merge it into `master`, as I am afraid to interfere in a wrong way with your changes related to the Fathers Day logo.
