### ISSUE TITLE
Sorting not working in Open for Reg section

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#1214]
Sorting by most recent doesn't seem to be working on the Open For Registration section at https://www.topcoder.com/challenges/

![image](https://user-images.githubusercontent.com/3812270/27230041-e81076ca-527b-11e7-81b4-cbb97cacff05.png)

**Comment by ajefts** [comment]
@tladendo fyi

**Comment by tladendo** [comment]
Looks like "most recent" sorts by submission end date. The current implementation is doing this correctly. Should it be set to sort by some other parameter?

**Comment by ajefts** [comment]
Please change it to registration start date. It should show the most recently posted challenges.

**Comment by tladendo** [comment]
got it, working on a PR
