### ISSUE TITLE
Update Cognitive Banner on Member Dashboard

### ISSUE THREAD

**Issue by harshitmehta123** [appirio-tech/topcoder-app#1237]
Update banner with attached image and link it to https://cognitive.topcoder.com/register/?utm_medium=banner&utm_source=topcoder&utm_campaign=cognitive-community

![cognitive-dashboard 1](https://user-images.githubusercontent.com/6296738/31587999-aceb5ad6-b1b9-11e7-88de-4eb1b72068ef.jpg)

**Comment by vikasrohit** [comment]
@sushilshinde it would be great if you can take it.

**Comment by sushilshinde** [comment]
@vikasrohit done! 

`298e15ba8e537919d5f2c953b3018083f4017c57`

**Comment by vikasrohit** [comment]
Thanks @sushilshinde 👍

**Comment by sushilshinde** [comment]
@vikasrohit it's on `dev`

**Comment by vikasrohit** [comment]
Do you know expected time for the next release? @harshitmehta123 needs it asap on production.
