### ISSUE TITLE
Filter Search should not do text search

### ISSUE THREAD

**Issue by RiteshTC** [appirio-tech/topcoder-app#1268]
Steps
Filter by technology tag by selecting AI.

Result:
The result includes challenges where challenge title or tags contains AI.

Expected Result:
Should search on technology tags only and not full text.

<img width="1296" alt="keywordsearch" src="https://user-images.githubusercontent.com/5771673/36013927-09207884-0d8d-11e8-93a9-ec30bcf9a464.png">
 
@birdofpreyru @ajefts

**Comment by birdofpreyru** [comment]
Moved into the correct repo: topcoder-platform/community-app#778
