### ISSUE TITLE
Past challenges search is not working

### ISSUE THREAD

**Issue by JayaDhaka** [appirio-tech/topcoder-app#1310]
This link https://www.topcoder.com/challenges?filter[text]=movidius&bucket=past is not working.

Steps to reproduce:

1. go to topcoder.com/challenges
2. Put "movidius" as the search term.
3. then select past challenges.

Please fix it.
![image 1](https://user-images.githubusercontent.com/34749364/40712862-539f44f4-641c-11e8-903d-5d60a75567da.png)

@birdofpreyru

**Comment by birdofpreyru** [comment]
It works, just very sub-optimal, in case of past challenges: while you see these placeholders it keeps on loading more and more past challenges, but is not able to find any matching the input text, thus you don't see any results showing up in the listing.

I moved the issue into the correct repo, and will further check, whether we are in position to improve this.

**Comment by rsial2** [comment]
Hey @birdofpreyru this does not work - if you try to search for "intel" or "movidius" (which are both past challenges), you will not get any results. So it is a true defect.
