### ISSUE TITLE
Getting an error "Failed to add user trait" on profile page

### ISSUE THREAD

**Issue by JayaDhaka** [appirio-tech/topcoder-app#1315]
While updating first name, last name and country on this URL https://www.topcoder.com/settings/profile, the user is getting an error "Failed to add user trait".
Please check and fix the issue.

![user error](https://user-images.githubusercontent.com/34749364/45407557-59e7be00-b687-11e8-83be-bb6bf64fa6f8.png)

**Comment by ThomasKranitsas** [comment]
@JayaDhaka this should be in the community-app repo.

I'm the copilot on that part of the platform so feel free to assign all related tickets to me.

I'll move this over to the correct repo and I'll close this ticket.

**Comment by pedrosorama** [comment]
Still same issue :)...
![image](https://user-images.githubusercontent.com/1439267/55497794-642cd200-5642-11e9-9b14-87abbdf85620.png)

**Comment by ThomasKranitsas** [comment]
@pedrosorama we've done quite some fixes that are not yet deployed. This should be resolved in the next deployment
