### ISSUE TITLE
Profile setting birthday is unfriendly

### ISSUE THREAD

**Issue by iversonLv** [appirio-tech/topcoder-app#1316]
_Do search, seems no issue related this or please ignore and close this issue._
Just found birthday datepicker can't select year? That is really unfriendly. 
Member must click left arrow back to many year to select their birthday year.

![image](https://user-images.githubusercontent.com/4952611/47444716-b17e5b00-d7e9-11e8-9815-275813e41c61.png)

**Comment by ThomasKranitsas** [comment]
We're working on this. Closing this ticket as we already have another ticket to address this issue.
