### ISSUE TITLE
Cleanup data structures for external accounts and external web links

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/topcoder-app#605]
For external accounts, we are nesting the added external account one more deep level e.g.

```
{
    status: 'SUCCESS' | 'ERROR',
    linkedAccount: {
        provider: 'github',
        data: {
            handle: '',
            status: 'PENDING',
            ...
        }
    }
}
```

while for external web links, it is
```
{
    provider: 'weblink',
    data: {
        handle: '',
        url: '',
        title: '',
        status: 'PENDING'
    }
}
```
@parthshah Can you please suggest which is the good candidate to be fixed here?

**Comment by parthshah** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30053585/?type=develop&noncache=true

**Comment by vic-appirio** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30053979/?type=develop&noncache=true

**Comment by nlitwin** [comment]
What needs to be done on this one? Do we need/want a challenge for this? At this point it's a fairly old issue.

**Comment by vikasrohit** [comment]
While the requirement is simple (to have same data structure for both web links and ext accounts), any change in data structure or code for ext accounts/links, can produce regressions. I think we can safely close this as things are working fine (I am assuming that because I don't have issues assigned for ext accounts) right now.

**Comment by nlitwin** [comment]
ok sounds good!
