### ISSUE TITLE
$25 - Support Back button when clicking on SRM card

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/topcoder-app#673]
JIRA: https://appirio.atlassian.net/browse/SUP-2909

**Steps to reproduce**
1. Navigate to https://www.topcoder-qa.com/members/sky_/details/?track=DEVELOP&subTrack=ASSEMBLY_COMPETITION . User is defaulted to statistics tab. 
1. Click on "challenges tab" and then click on a Challenge title. 
1. User is navigated to challenge detail
1. Click back button, user is redirected to "Statistics tab"

**Expected:** 
User should be redirected back to "challenges tab".

**Comment by iit2009060** [comment]
working

**Comment by Colinh84** [comment]
Since above user doesn't seem to be working on this and it has been over 4 days, can I take this issue? Topcoder contest rules said there was a 2-day limit..

**Comment by huangqun** [comment]
@Colinh84 You can take it

**Comment by Colinh84** [comment]
ok thanks, working on it.

**Comment by Colinh84** [comment]
submitted merge request. Make sure to clear browser cache before testing.

**Comment by nlitwin** [comment]
Thanks @Colinh84, I added a comment in the PR and merged it in.
