### ISSUE TITLE
$25 - User need to click twice on 'Back to Dashboard' to redirect to the dashboard from 'My Challenges' page.

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/topcoder-app#674]
JIRA: https://appirio.atlassian.net/browse/SUP-2746

** Steps to Reproduce**
1. Login to application.
2. Click on the 'Past Challenges' link on dashboard.
3. Click on the "Active' tab.
4. Click on the 'Back to Dashboard'.
5. Verify the page.

**Comment by shubhendusaurabh** [comment]
@huangqun can't reproduce

**Comment by nlitwin** [comment]
I can't reproduce this either. Can we close this? @parthshah @fnisen @vikasrohit

**Comment by vikasrohit** [comment]
Yes, I think we can close this and if in case it appears again we can create new issue in future.
