### ISSUE TITLE
$30 - Dashboard--> "Practice on past problems" should be displayed properly on SRM on IE 11.

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/topcoder-app#676]
JIRA: https://appirio.atlassian.net/browse/SUP-2698

** Steps to reproduce ** : 
Login to account and verify SRM section on dashboard in IE11.
![capture-for-jira-screenshot-20151118-232245-491](https://cloud.githubusercontent.com/assets/1987710/12435554/0d81c75e-bec3-11e5-8017-33d93edfee96.png)

**Comment by Colinh84** [comment]
Working on this.

**Comment by Colinh84** [comment]
I noticed the same issue was happening with tooltips in IE11, so I corrected that problem as well in my fix.

**Comment by huangqun** [comment]
fixed
