### ISSUE TITLE
$15 - My dashboard--> Challenges cards--> clicking on Posts/Registrants/Submissions icons should navigate user to appropriate link

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/topcoder-app#677]
JIRA: https://appirio.atlassian.net/browse/SUP-2675

** Steps to reproduce**:
Login to application
Open my dashboard
Click on post under my challenges section
Expected:- Forums should get opened up
Actual:- Forums not getting opened up, redirecting to view registrants page
http://screencast.com/t/Y6jPoHXpLV

**Comment by shubhendusaurabh** [comment]
working
