### ISSUE TITLE
$40 - For skills type ahead list the matches in alpha order

### ISSUE THREAD

**Issue by nlitwin** [appirio-tech/topcoder-app#684]
JIRA: https://appirio.atlassian.net/browse/SUP-2451

Steps to reproduce:
 - Log in
 - Navigate to settings
 - Under 'Country to Represent', type any letter
 - Under 'Add a new skill', type any letter.

Result - the first results do not all start with the letter that you typed
Expected result - the results that start with the letter you typed should be listed first

Currently we are using the angular directive angucomplete-alt (https://github.com/ghiden/angucomplete-alt)

Angucomplete-alt does not currently support sorting in the way that we want, as explained above. We would like to swap out angucomplete-alt with react-select (https://github.com/JedWatson/react-select). We've wrapped the React component in an angular directive with the name "dropdown". You can see an example of it being used here on line 6: https://github.com/appirio-tech/topcoder-app/blob/dev/app/directives/tc-form-fonts/tc-form-fonts.jade

**Comment by shubhendusaurabh** [comment]
working

**Comment by shubhendusaurabh** [comment]
@nlitwin new version of angucomplete-alt i.e. v2.2 supports custom sorting through functions.
Is it acceptable to update angucomplete-alt and fix this through custom sorting function instead of switching to react-select?

**Comment by nlitwin** [comment]
Thanks @shubhendusaurabh for your comment. Unfortunately, we'd like to deprecate angucomplete-alt, since we're slowly moving to react components.

**Comment by Colinh84** [comment]
working on this.

**Comment by nlitwin** [comment]
Merged. Thanks, all!
