### ISSUE TITLE
$25 - Add TCO icon/link to the navigation

### ISSUE THREAD

**Issue by nlitwin** [appirio-tech/topcoder-app#694]
JIRA ticket: https://appirio.atlassian.net/browse/SUP-2952

This change must be done on multiple repositories.

Task: 

Add TCO icon under Community, second in the order (behind "Overview"). The icon should link to: http://tco16.topcoder.com/.

The icons should be under ~/topcoder-app/assets/images/nav  
Position: Community, after Overview
Icon: ico-tco16.svg; Title: TCO 2016, URL: http://tco16.topcoder.com/

![screen shot 2016-01-26 at 3 34 25 pm](https://cloud.githubusercontent.com/assets/3812270/12703865/8e5a8ee0-c81b-11e5-8449-85c1fed14a5c.png)

**Comment by shubhendusaurabh** [comment]
@nlitwin @huangqun can't view jira. please update here

**Comment by ajefts** [comment]
Updated the content of the task. Please let us know if you need any more info.  Thanks.

**Comment by shubhendusaurabh** [comment]
@ajefts Thanks but I can't find the required tco16 icon. Is it already included?

**Comment by ajefts** [comment]
Icon attached. 

[ico-tco16.svg.zip](https://github.com/appirio-tech/topcoder-app/files/112605/ico-tco16.svg.zip)
