### ISSUE TITLE
Text overlap in the container 

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#830]
Description
-----------------------------------------------------------------
Text overlap in the container 

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Drag and drop a file to the container

Expected Result(s)
-----------------------------------------------------------------
- Must not overlap

Actual Result
-----------------------------------------------------------------
- Text overlap in the container 

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-06-25_12-06-19](https://cloud.githubusercontent.com/assets/4592712/16355433/3971bbc0-3ad4-11e6-8149-a68836e2bd84.png)

**Comment by skyhit** [comment]
UI issue, not related to the scope to test.

**Comment by mdesiderio** [comment]
@parthshah duplicate
