### ISSUE TITLE
Without uploading anything e-mail is received, Must validate before hitting the SUBMIT button (Because they are mandatory fields)

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#831]
## Description

Without uploading anything e-mail is received, Must validate before hitting the SUBMIT button (Because they are mandatory fields)
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Don't upload any documents
- Agree and Click Submit
## Expected Result(s)
- Must not receive an email, Must validate the input before submitting the items
- Must validate if user upload their Submission, source and preview file before hitting the SUBMIT button
## Actual Result
- Without uploading e-mail is received 
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![4](https://cloud.githubusercontent.com/assets/4592712/16355478/48dd1b12-3ad5-11e6-9b1e-f15c320c32c6.png)

**Comment by sdgun** [comment]
http://www.screencast.com/t/jV9dZGwb

**Comment by skyhit** [comment]
@sdgun this is more like UI issue.

**Comment by sdgun** [comment]
@skyhit No this is a functional issue:

If the Submission, source and preview files are mandatory, must validate them before clicking the SUBMIT button. Because if user forgot to upload one of the files, let's says the most important file as 'Source File - PSD' but the system sent an e-mail saying 'Your submission to the following challenge has been uploaded successfully' 

Then the user will think he/she has uploaded all the required documents. If we validate them before, user will know he/she forgot to upload the source file.

**Comment by mdesiderio** [comment]
Duplicate (or at least the same problem) of https://github.com/appirio-tech/topcoder-app/issues/835
