### ISSUE TITLE
Long scrollbar displayed in the 'Uploading submission' page

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#832]
## Description

Long scrollbar displayed in the 'Uploading submission' page
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Drag and drop a file to the container
- Attached all the required docs
- Agree and Click Submit
- Check the scroll bar
## Expected Result(s)
- Must not display a long scroll bar
## Actual Result
- Long scrollbar displayed in the 'Uploading submission' page
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_12-36-37](https://cloud.githubusercontent.com/assets/4592712/16355436/57b4ef9e-3ad4-11e6-8cfc-10370c0b642d.png)

**Comment by mdesiderio** [comment]
@parthshah

**Comment by vikasrohit** [comment]
@parthshah Do we really need upload progress modal now? I guess, as individual file is already uploaded to the filestack's staged server and progress is shown for individual item, we may not need this customer progress bars. We even don't upload progress in the progress modal and it would seem to collapse without showing progress.
