### ISSUE TITLE
'Remove all' button is not required because there is only one item is displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#833]
## Description

'Remove all' button is not required because there is only one item is displayed
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Click PICK A FILE
- Select MY COMPUTER
- Click 'Choose a File'
- When uploading click cancel
- Check the list, there is a remove all button
- Now click MY COMPUTER
- Click 'Choose a File'
- When uploading click cancel
- Check the list it replaces the first file
## Expected Result(s)
- 'Remove all' button is not required because there is only one item is displayed
## Actual Result
- 'Remove all' button is displayed, but only one item is displayed
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_12-58-03](https://cloud.githubusercontent.com/assets/4592712/16355444/7d3c65b2-3ad4-11e6-8705-36d5d94b4d6d.png)

**Comment by mdesiderio** [comment]
@parthshah, not sure if this is something we can change in the filestack widget
