### ISSUE TITLE
Can click SUBMIT button without uploading files

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#834]
Description
-----------------------------------------------------------------
Can click SUBMIT button without uploading files

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Scroll down and check the 'I UNDERSTAND AND AGREE'
- Click SUBMIT

Expected Result(s)
-----------------------------------------------------------------
- Must validate it

Actual Result
-----------------------------------------------------------------
- Can click SUBMIT button without uploading files

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
http://www.screencast.com/t/IQxFvRoQKS

**Comment by mdesiderio** [comment]
@parthshah

**Comment by parthshah** [comment]
merged fix to dev.
