### ISSUE TITLE
'Your submission to the following challenge has been uploaded successfully' e-mail sent even we SUBMIT without uploading files

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#835]
## Description

'Your submission to the following challenge has been uploaded successfully' e-mail sent even we SUBMIT without uploading files
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Scroll down and check the 'I UNDERSTAND AND AGREE'
- Click SUBMIT
- Check the mail
## Expected Result(s)
- Must not receive email stating "'Your submission to the following challenge has been uploaded successfully' " if we don't upload files
## Actual Result
- 'Your submission to the following challenge has been uploaded successfully' e-mail sent even we SUBMIT without uploading files
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_13-15-09](https://cloud.githubusercontent.com/assets/4592712/16355535/dee28f9c-3ad6-11e6-92ad-4ba8edb43f70.png)

**Comment by mdesiderio** [comment]
@parthshah I think we should fix this one in the frontend, as the service doesn't check if the files were downloaded or not. I think we need to make sure we don't change the status of the submission to PROCESS_PENDING if uploads didn't complete
