### ISSUE TITLE
File upload progress bar is not working

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#836]
## Description

File upload progress bar is not working
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Upload the required files
- Click SUBMIT
- Check the progress bar
## Expected Result(s)
- Progress bar must work
## Actual Result
- File upload progress bar is not working
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_12-36-51](https://cloud.githubusercontent.com/assets/4592712/16355496/a6556b1e-3ad5-11e6-94a1-fde5a11639a5.png)

**Comment by sdgun** [comment]
http://www.screencast.com/t/zemVoD2oE6f7

**Comment by mdesiderio** [comment]
@parthshah

**Comment by parthshah** [comment]
can not reproduce.
