### ISSUE TITLE
Deep link files; upload fails

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#837]
Description
-----------------------------------------------------------------
Deep link files; upload fails

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Upload the required files
- Add Deep link files to one of the SUBMISSION/SOURCE (Use the attached File)
- Click SUBMIT
- Check the progress

Expected Result(s)
-----------------------------------------------------------------
- Must able to uplaod deeplink files

Actual Result
-----------------------------------------------------------------
- Deep link files; upload fails

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
https://www.dropbox.com/s/rwtstf4md52codt/Deep%20Folder%20Structure.zip?dl=0

**Comment by sdgun** [comment]
![2016-06-25_13-13-57](https://cloud.githubusercontent.com/assets/4592712/16355528/bf2e370a-3ad6-11e6-823b-fca856f52b8a.png)

**Comment by skyhit** [comment]
@sdgun what is Deep Link files?

**Comment by sdgun** [comment]
Folders within folders: Sample file https://www.dropbox.com/s/rwtstf4md52codt/Deep%20Folder%20Structure.zip?dl=0

**Comment by mdesiderio** [comment]
@parthshah probably a filestack limitation

**Comment by parthshah** [comment]
@vikasrohit can you please investigate

**Comment by vikasrohit** [comment]
@parthshah @mdesiderio I am not able to reproduce the issue with the given sample file... its being successfully uploaded for me on local.
