### ISSUE TITLE
Submission/Source/Preview Image boxes are attached to each other in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#838]
## Description

Submission/Source/Preview Image boxes are attached to each other in IE11
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- Check the Submission/Source/Preview Image boxes spacing
## Expected Result(s)
- Must have some space in between them as in other browsers
## Actual Result
- Submission/Source/Preview Image boxes are attached to each other in IE11
## Environment
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_12-05-51](https://cloud.githubusercontent.com/assets/4592712/16355422/da2c3b4a-3ad3-11e6-90b4-706ccee6b2e2.png)

**Comment by skyhit** [comment]
@sdgun UI issue, will not counted

**Comment by mdesiderio** [comment]
@parthshah

**Comment by parthshah** [comment]
@vikasrohit .. can you please look into this css issue.

**Comment by birdofpreyru** [comment]
Tested on Win 10, IE 11, the issue seems to be fixed already, thus I am closing it.
![tmp-3](https://cloud.githubusercontent.com/assets/20144632/22226925/d998e48e-e1c8-11e6-85e8-035b56eeb6fb.png)
