### ISSUE TITLE
After uploading a file to Submission/Source/Preview Image boxes; info text must remove

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#839]
Description
-----------------------------------------------------------------
After uploading a file to Submission/Source/Preview Image boxes; info text must remove

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; There is a info text
- Now drag and drop  file to one of the above items
- Check the text

Expected Result(s)
-----------------------------------------------------------------
- After uploading a file to Submission/Source/Preview Image boxes; info text must remove
- Must remove the info text: 

Actual Result
-----------------------------------------------------------------
- After uploading a file to Submission/Source/Preview Image boxes; info text is not removed

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-06-25_12-05-51](https://cloud.githubusercontent.com/assets/4592712/16355420/b488126a-3ad3-11e6-9c4a-ac402e887ec3.png)

**Comment by sdgun** [comment]
![3](https://cloud.githubusercontent.com/assets/4592712/16355427/1f15ae62-3ad4-11e6-8587-fb9518eae81c.png)

**Comment by skyhit** [comment]
@sdgun this is because you uploaded a wrong file, it needs zip.

**Comment by sdgun** [comment]
@skyhit Even we upload a zip file the default messages is also there.

**Comment by mdesiderio** [comment]
FYI @parthshah

**Comment by parthshah** [comment]
@vikasrohit is this something that we can control?
