### ISSUE TITLE
No need to display a scroll bar in the 'Choose File' dialog in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#840]
## Description

No need to display a scroll bar in the 'Choose File' dialog in IE11
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; There is a info text
- Click PICK A FILE
- Check the Scroll Bar
## Expected Result(s)
- No need to display a scroll bar in the 'Choose File' dialog in IE11
## Actual Result
- Scroll bar displayed in the 'Choose File' dialog in IE11
## Environment
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_12-51-58](https://cloud.githubusercontent.com/assets/4592712/16355419/a1f2a9b2-3ad3-11e6-9a3e-d791ad7a8a84.png)

**Comment by skyhit** [comment]
UI issue, not counted.

**Comment by mdesiderio** [comment]
FYI @parthshah probably a filestack bug that we can't fix.
