### ISSUE TITLE
[SUBMISSION / SOURCE] No validation for 500MB+ Files

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#841]
## Description

[SUBMISSION / SOURCE] No validation for 500MB+ Files
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Upload a 500MB+ file to SUBMISSION / SOURCE
- Check the response
## Expected Result(s)
- Need to have a validation message when user is going to upload a 500MB+ Files
## Actual Result
- No validation for 500MB+ Files
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_12-43-29](https://cloud.githubusercontent.com/assets/4592712/16355381/76f9618e-3ad2-11e6-91c3-0262a1d2bfb4.png)

**Comment by sdgun** [comment]
http://www.screencast.com/t/KxXjRBIvQ

**Comment by skyhit** [comment]
UI issue. you need to future check if that can be properly proceed.

**Comment by sdgun** [comment]
@skyhit This is a functional I think; (This is about a validation issue) When you try to upload a 500MB+ file from PICK A FILE option, there is a validation.

But when we drag and drop a 500MB+ file here there is no validation and we can't drag and drop any other files to that placeholder. Please recheck it again.

![2016-06-26_18-40-58](https://cloud.githubusercontent.com/assets/4592712/16362483/8e0460f8-3bcd-11e6-8fd8-b793ba8e1753.png)

**Comment by mdesiderio** [comment]
FYI @parthshah

**Comment by parthshah** [comment]
This seems to be a problem with Filepicker again. Drag and drop doesn't display file is too big error message. But I was able to upload a file with valid size after that. Will follow up with filestack but I think this is a lower priority fix.
@fnisen fyi
