### ISSUE TITLE
Confirmation message displayed twice when we cancel the popup

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#842]
Description
-----------------------------------------------------------------
Confirmation message displayed twice when we cancel the popup

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Click PICK A FILE
- Upload a 6MB+ file to SUBMISSION / SOURCE
- Click close button of the popup model
- Click Cancel from the validation popup
- It will show it again

Expected Result(s)
-----------------------------------------------------------------
- Confirmation popup must display once

Actual Result
-----------------------------------------------------------------
- Confirmation message displayed twice when we cancel the popup

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
http://www.screencast.com/t/RLgPEGNNzVO

**Comment by skyhit** [comment]
UI issue.

**Comment by mdesiderio** [comment]
FYI @parthshah probably another filestack bug.

**Comment by parthshah** [comment]
Bug with Filestack
