### ISSUE TITLE
'declaration.txt' is not included in the submission zip

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#844]
## Description

'declaration.txt' is not included in the submission zip
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Click PICK A FILE
- Upload a 6MB+ file to SUBMISSION
- Upload a SOURCE file
- And also the Preview file
- Declare a FONT (important)
- Agree and click SUBMIT
- Now go to OR or Design page
- (https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30049552)
- (https://studio.topcoder-dev.com/?module=ViewSubmission&ct=30049552)
- Then download the file and check the file inside
## Expected Result(s)
- 'declaration.txt' must included in the submission zip
## Actual Result
- 'declaration.txt' is not included in the submission zip
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
https://www.dropbox.com/s/mko440gdv63w50h/1466812800.zip?dl=0

**Comment by mdesiderio** [comment]
@skyhit I could not reproduce this one. It is possible that it is a slight misunderstanding, the declaration file is injected into the submission file, that is inside the submission folder of the zip that is downloaded from studio.

**Comment by skyhit** [comment]
@mdesiderio yes, I can not reproduce it too.
