### ISSUE TITLE
Specified ranking from the upload page won't effect to the design page listing

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#845]
## Description

Specified ranking from the upload page won't effect to the design page listing
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Click PICK A FILE
- Upload a file to SUBMISSION
- Upload a SOURCE file
- And also the Preview file
- Declare a FONT (important)
- Set the RANKING as #2
- Agree and click SUBMIT
- Now go to Design page
- (https://studio.topcoder-dev.com/?module=ViewSubmission&ct=30049552)
- Check the listing
## Expected Result(s)
- Specified ranking from the upload page must effect to the design page listing
## Actual Result
- Specified ranking from the upload page won't effect to the design page listing
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_12-40-01](https://cloud.githubusercontent.com/assets/4592712/16355372/56da133a-3ad2-11e6-91d7-2ca0b24226f3.png)

**Comment by mdesiderio** [comment]
@skyhit I was not able to reproduce this one ... Also there seems to be a discrepancy between the text and the image. The text says to set the submission rank to 2, and the image said the rank was supposed to be one.

Please try again and provide more detailed steps on how to reproduce this. A recording would help.

**Comment by skyhit** [comment]
@mdesiderio yep, I can not reproduce it too.
