### ISSUE TITLE
Empty zip files are recognized as valid 

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#846]
## Description

Empty zip files are recognized as valid 
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Click PICK A FILE
- Upload a file to SUBMISSION (empty zip file) https://www.dropbox.com/s/bv1vuw1cndgyk92/New%20folder.zip?dl=0
- Upload a SOURCE file (empty zip file) https://www.dropbox.com/s/bv1vuw1cndgyk92/New%20folder.zip?dl=0
- And also the Preview file (PNG File)
- Declare a FONT (important)
- Set the RANKING as #1
- Agree and click SUBMIT
## Expected Result(s)
- Must validate it
- It will reduce server requests
## Actual Result
- Empty zip files are recognized as valid
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

**Comment by sdgun** [comment]
![2016-06-25_13-30-40](https://cloud.githubusercontent.com/assets/4592712/16355596/0b36221e-3ad9-11e6-9379-a5222fe01b92.png)

**Comment by skyhit** [comment]
UI issue, what if it is submitted?

**Comment by sdgun** [comment]
@skyhit It is recognizes as a valid file

**Comment by skyhit** [comment]
yes, for client side, empty can be allowed.
