### ISSUE TITLE
"Drag and Drop your zip file here" must remove from the "Preview Image" section

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#847]
Description
-----------------------------------------------------------------
"Drag and Drop your zip file here" must remove from the "Preview Image" section

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Check the "Preview Image" section

Expected Result(s)
-----------------------------------------------------------------
- Must display as "Drag and Drop your PNG or JPG file here" in the "Preview Image" section

Actual Result
-----------------------------------------------------------------
- "Drag and Drop your zip file here" must remove from the "Preview Image" section

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------
![2016-06-25_13-45-31](https://cloud.githubusercontent.com/assets/4592712/16355654/25ef8706-3adb-11e6-8012-df16144accbc.png)

**Comment by skyhit** [comment]
UI issue.

**Comment by mdesiderio** [comment]
@parthshah
