### ISSUE TITLE
Previous uploaded percentage displayed when we upload a new file

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#848]
Description
-----------------------------------------------------------------
Previous uploaded percentage displayed when we upload a new file

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Click on the "Submission" section
- Drag and drop a file (25+MB) and wait till 10%
- Click Cancel
- NOw remove the half uploaded file
- Drag and drop a new file (25+MB)
- Check the starting %

Expected Result(s)
-----------------------------------------------------------------
- Must not display the previous values

Actual Result
-----------------------------------------------------------------
- Previous uploaded percentage displayed when we upload a new file

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
http://www.screencast.com/t/viH0dZQk1cIh

**Comment by skyhit** [comment]
UI issue.

**Comment by sdgun** [comment]
@skyhit I think this is a functional issue. When we upload a file and cancel it when it reaches 10% and then re-upload the file again will show the 10% and then reset the upload percentage value. Please re-check again.

**Comment by mdesiderio** [comment]
@parthshah this is FYI, I don't think we can fix this, as it is a bug in the filestack component, but maybe we want to report to them as an issue?

**Comment by parthshah** [comment]
Yep, this is definitely a filestack ui issue. I dont think its a big deal since it does reset to 0%.
