### ISSUE TITLE
"Remove" button is hard to find when we upload a file with a long name

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#849]
Description
-----------------------------------------------------------------
"Remove" button is hard to find when we upload a file with a long name

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Click on the "Submission" section
- Drag and drop a file with long name (eg: 32738A6E00000578-3504412-image-a-6_145865451734132738A6E00000578-3504412-image-a-6_145865451734132738A6E00000578-3504412-image-a-6_145865451734132738A6E00000578-3504412-image-a-6_1458654517341) --> sample file attached
- Check the remove button

Expected Result(s)
-----------------------------------------------------------------
- Must trim the log file names with (...)

Actual Result
-----------------------------------------------------------------
- "Remove" button is hard to find when we upload a file with a long name

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------
![2016-06-25_14-01-36](https://cloud.githubusercontent.com/assets/4592712/16355714/9beb402e-3add-11e6-9356-ab9ce007372c.png)

**Comment by sdgun** [comment]
![32738a6e00000578-3504412-image-a-6_145865451734132738a6e00000578-3504412-image-a-6_145865451734132738a6e00000578-3504412-image-a-6_145865451734132738a6e00000578-3504412-image-a-6_1458654517341](https://cloud.githubusercontent.com/assets/4592712/16355716/aad07dfc-3add-11e6-85f2-007fad9aec57.jpg)

**Comment by skyhit** [comment]
UI issue.

**Comment by mdesiderio** [comment]
@parthshah
