### ISSUE TITLE
Try again button is not working

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#850]
## Description

Try again button is not working
## Steps to Reproduce
- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- Click PICK A FILE
- Upload a file to SUBMISSION
- Upload a SOURCE file
- And also the Preview file
- Declare a FONT (important)
- Set the RANKING as #2
- Agree and click SUBMIT
- When the file upload fails
- Click Try again from the page
## Expected Result(s)
- 'Try again' must work
## Actual Result
- Try again button is not working
## Environment
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)
## Image/Video/JS Log (If not attached, Please check the comments section) 

![2016-06-25_13-15-51](https://cloud.githubusercontent.com/assets/4592712/16357822/4c6cfcee-3b1f-11e6-8f28-64985d62e831.png)

**Comment by skyhit** [comment]
UI issue.

**Comment by sdgun** [comment]
@skyhit I am talking about the functionality of the "try Again' button. not the layout issue. I think when we press it must try to upload the files again

**Comment by mdesiderio** [comment]
FYI @parthshah

**Comment by parthshah** [comment]
'try again' should take the user back to the submission page. It doesn't automatically re-try uploading the file.
