### ISSUE TITLE
'Your submission to the following challenge has been uploaded successfully' e-mail sent even we SUBMIT wrong files (rar)

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/topcoder-app#851]
Description
-----------------------------------------------------------------
'Your submission to the following challenge has been uploaded successfully' e-mail sent even we SUBMIT wrong files (rar)

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://www.topcoder-dev.com/challenge-details/30049552/?type=design&nocache=true)
- Login as valid user
- Register
- Open the contest page an click 'Submit your entries' button
- (https://www.topcoder-dev.com/challenges/30049552/submit/file/)
- In the Submission/Source/Preview Image boxes; 
- To the "Submission" and "Source" sections
- Drag and drop a rar file 
- Upload a preview file
- Click Submit
- Check the mails
- Upload fails e-mail received, but after some time 'Your submission to the following challenge has been uploaded successfully' e-mail received

Expected Result(s)
-----------------------------------------------------------------
- Must not sent that e-mail when user uploads wrong file types

Actual Result
-----------------------------------------------------------------
- 'Your submission to the following challenge has been uploaded successfully' e-mail sent even we SUBMIT wrong files (rar)

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 51.0.2704.106 m
- **Operating System:** Windows 7 Pro 64bit (SP 1)

Image/Video/JS Log (If not attached, Please check the comments section) 
-----------------------------------------------------------------
![4](https://cloud.githubusercontent.com/assets/4592712/16357866/20d1de50-3b20-11e6-938c-d383900646bd.png)

**Comment by skyhit** [comment]
but you will receive not proceed email, right?

**Comment by sdgun** [comment]
@skyhit Yes I am getting 'Failed' message,  but after that I am getting "Your submission to the following challenge has been uploaded successfully: " message 

So I think this will confuse the users. After the fail message why are we getting this message?

**Comment by parthshah** [comment]
Can't reproduce this now. Filepicker validations won't allow rar file extension.
