### ISSUE TITLE
Upload submission link in the mail sent after registration does not direct to  submission page.

### ISSUE THREAD

**Issue by trupti1113** [appirio-tech/topcoder-app#852]
**Steps to Reproduce:**
1. Register for the challenge.
2. An email is generated informing the candidate  of the registration.
3.Click on the submission link provided in the email

**Expected Result:**
The submission link provided in the registration email should redirect you to the submission page to upload the submission files.

**Actual:**
A default page with no facility to upload submission files is displayed.
To actually upload the submission file the user needs to navigate back to the challenge page.

**Environment:**
OS: Windows 7
Browser: Google Chrome

Bug Screenshots attached
[Bug screenshots.docx](https://github.com/appirio-tech/topcoder-app/files/333389/Bug.screenshots.docx)

**Comment by skyhit** [comment]
this is a valid issue, but not related to the scope to test with
