### ISSUE TITLE
Switch topcoder app to member service search URLs instead of internal-api  (lambda)

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/topcoder-app#901]
Member Service now supports member search and suggest features. Please switch internal-api.topcoder.com/v3/members/_search to point to https://api.topcoder.com/v3/members/_search instead.

fyi - @fnisen. 
Once this is done we can deprecate internal-api.topcoder.com member lambda function.

**Comment by vikasrohit** [comment]
@parthshah @fnisen There are few more URLs that are using internal-api URL:

<pre>
export const memberSearchTagUrl = ${INTERNAL_API}/tags/
export const leaderboardUrl = ${INTERNAL_API}/leaderboards/
</pre>

**Comment by vikasrohit** [comment]
bump up

**Comment by parthshah** [comment]
memberSearchTagUrl : https://api.topcoder.com/v3/tags/?filter=name%3Djava
We dont have an endpoint for leaderboard yet though. I'll have Fireice run a challenge to migrate that to member service

**Comment by parthshah** [comment]
@vikasrohit leaderboard API is now available through member service as well. https://api.topcoder.com/v3/leaderboards... please change the this urls.

**Comment by vikasrohit** [comment]
@parthshah  Done. Deployed changes to dev.

**Comment by vikasrohit** [comment]
@parthshah It seems we need to publish the topcoder-app-r's new release to npm registry to get the changes reflected into topcoder-app. I tried doing that however, I don't have permissions to do that. I think Nick is the owner of the repo. I am not sure how we can publish now.

**Comment by fnisen** [comment]
I can ask Nick to reassign ownership, if you tell me exactly what you need... unless you guys have other ideas.

**Comment by vikasrohit** [comment]
Its better to transfer ownership to non personal account. I have workaround for now by pointing the topcoder-app to specific branch of the topcoder-app-r. @parthshah Do you have any other idea?

**Comment by vikasrohit** [comment]
Just saw that @parthshah  has updated the release of both topcoder-app-r and topcoder-app which reflected the changes in dev environment. Thanks Parth.

@fnisen We don't need to change the ownership now as Parth fixed it with github releases instead of npm publish. However, I think from ownership perspective, we should transfer all ownerships to a non personal account.
