### ISSUE TITLE
[$30] - Add Predix badges to profiles

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#912]

**Comment by ajefts** [comment]
@talesforce Let's chat about this one tomorrow.  I'd like to get this going relatively soon. It involves adding a couple new badges to the existing badge framework.

**Comment by ajefts** [comment]
Here are the images for the badges.

[tc-predix-community-badge.zip](https://github.com/appirio-tech/topcoder-app/files/699268/tc-predix-community-badge.zip)

@talesforce Can we get these added to the current sprite for the badges and get the profile page updated so it uses the new sprite? These badges should show up like the other badges do on the profile page.

We will be adding the data for the badge assignment separately, so you can assume that part is done.

**Comment by birdofpreyru** [comment]
@ajefts Do you mean by badges the image shown in the Skills section of the Profile page? It looks to me, there is no sprite for those, they are just stored and served as separate .svg images.

**Comment by ajefts** [comment]
Thanks for jumping in @birdofpreyru .  This is one we need to get done soon.

I'm referring to the badge modal you see if you click "Badges" under your profile pic:

![image](https://cloud.githubusercontent.com/assets/3812270/22073837/74b572a6-dd74-11e6-9d7a-310ad33b865f.png)


I believe it uses sprites like these:  https://github.com/appirio-tech/topcoder-app/blob/dev/assets/images/badge.grid.large.png

So, we need to get the sprite updated and the code logic that defines which badge to display based on the given badge id.

@dmessing Do you have your scripts handy for manually assigning badges?  Can you attach them here please?

**Comment by birdofpreyru** [comment]
Yeap, I've never seen these badges before, but just discovered them, and was about to edit my question here :)

So, it is ok, that most of the badges come in the groups with kind of progress bar, and your Predix Badge is just a square icon? I mean, when added, the Predix Badge should be just shown centred at a new line in that modal?
