### ISSUE TITLE
[$20] - Documents attached to challenge page are not visible once the submission phase is over

### ISSUE THREAD

**Issue by Schpotsky** [appirio-tech/topcoder-app#918]
Once the submission phase is over, the documents attached under the "Downloads" section of a challenge details page are not available for download. it shows the following message "Downloads are no longer available for this challenge".

So, a reviewer needs to download the documents during the submission phase.

If a reviewer is assigned after the end of the submission phase, he/she will not be able to access the documents attached in the challenge details page.

**Comment by talesforce** [comment]
@Schpotsky - This has always worked like this in the past as well. I will discuss with @ajefts if we intend to change this behaviour.

**Comment by birdofpreyru** [comment]
@ajefts Should we change it so that Downloads stay available till the end of the review phase?

**Comment by ajefts** [comment]
We can actually change it so they are available until the end of appeals response, or end of review if there is no appeals.  However, these are not public attachments, so it should still be limited based on having a role on the challenge.  I believe the current API should be checking that already.

**Comment by birdofpreyru** [comment]
EXPECTED FIX:

Change the deadline after which attachments under `Downloads` section of a challenge details page to be equal to the moment the challenge is over and the winners are known (i.e. either the end of the appeals response phase, or the end of the appeals phase, if there were no appeals). All other rules concerning the access to the attachments should stay the same as now.

**Comment by shubhendusaurabh** [comment]
appirio-tech/tc-site/pull/460
