### ISSUE TITLE
[$60] - User menu is missing at the challenge listing page

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#932]
Challenge listing page:
![screenshot-2](https://cloud.githubusercontent.com/assets/20144632/22043838/c6360798-dd11-11e6-914e-e35b0029407c.png)

The Dashboard page with the menu missing at the previous screenshot marked with the red circle:
![screenshot-1](https://cloud.githubusercontent.com/assets/20144632/22043848/d4b74714-dd11-11e6-9b8b-51fc6c23c263.png)

Probably it is due to an error in JS code, visible in the first image (`_kmq is not defined`)

### Expected Fix

1. The User menu should be visible and working on all pages the same way it does in the Dashboard.
2. The reason of the `_kqm is not defined` error should be found out, and the error should be fixed.

NOTE: Probably, the challenge listing code itself is contained in this repo: https://github.com/appirio-tech/tc-site and it is that code, which should be fixed.

**Comment by lijulat** [comment]
@birdofpreyru Can I Get access to this ticket?

**Comment by birdofpreyru** [comment]
@lijulat It is yours :)

**Comment by lijulat** [comment]
@birdofpreyru Thanks

**Comment by lijulat** [comment]
@birdofpreyru 

https://github.com/appirio-tech/tc-site/pull/458
