### ISSUE TITLE
[$30] - Challenge details page needs some enhancements in its CSS styling

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#938]
### Expected Fix:
1. Have a look at this sample challenge page: https://www.topcoder.com/challenge-details/30056243/?type=develop&noncache=true
We need some corrections in CSS to make it look more pretty, than it is now.
    1. Spaces between headers and paragraphs should be corrected. The space between any header and the following paragraph should be equal to the current spacing between two paragraphs. The space before any header and the preceding paragraph should be larger than that.
    2. For H1 header please set the same style, as H2 header uses now. Keep H2 header the same as now. For H3 header increase the font size to match the size of text in the paragraphs. For H4-H6 paragraphs, reuse the same style as for H3, but with black text color.
    3. As you'll see in the end of the challenge overview section, italic text looks twice smaller than the regular text around it. Should be the same size.
    4. The header `Final Submission Guidelines` should H2 header.
    5. Headers in the `Final Submission Guidelines` section should be the same style as in the `Challenge Overview`.
    6. As you'll see, in the `Final Submission Guidelines` section, paragraph text has different style, depending whether it is wrapped inside `<p>` tag (then it looks the same like in the Challenge Overview) or not (the it is bolder and smaller). Please make it looks the same in both cases, as it looks now without the `<p>` tag (i.e. the bolder version).
2. To test it locally, you'll have to locally deploy this code: https://github.com/appirio-tech/tc-site Once setup it will work with the production database, so you'll be able to access this sample challenge from your locally deployed frontend, and to see the changes you are performing.

**Comment by ThomasKranitsas** [comment]
@birdofpreyru Can you add me on this one? Thanks!

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Ok, it is yours.

**Comment by ThomasKranitsas** [comment]
So the PR for this will be against the https://github.com/appirio-tech/tc-site repo and I'll just mention this ticket there, correct?

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Sure, all PR against the corresponding repos, just reference them from the original issue tickets, so that nothing is lost.

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Any update on it? Are working on it?

**Comment by ThomasKranitsas** [comment]
Hey @birdofpreyru! Sorry for the delay.. I'll submit PR in the next few hours

**Comment by birdofpreyru** [comment]
@ThomasKranitsas No worries, no need to hurry. Just checking that you have not forgot about it :)

**Comment by ThomasKranitsas** [comment]
@birdofpreyru I submitted a PR here: https://github.com/appirio-tech/tc-site/pull/462
