### ISSUE TITLE
[$20] - Update CAB members on the Community Overview page

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#939]
We need to update the CAB members with the 2017 list on this page:   

https://www.topcoder.com/community/members/

**Comment by ajefts** [comment]
@birdofpreyru I'm not sure if you have this one on the list, but if not let's add it.  This would be a really good one for someone to start with if they want to get used to the env...

**Comment by birdofpreyru** [comment]
### Expected Fix
Just update the CAB members section at that page with the new members.
The 2017 CAB members are listed here: https://www.topcoder.com/community/member-programs/topcoder-community-advisory-board/

**Comment by ThomasKranitsas** [comment]
Can I work on this one?

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Sure :)

**Comment by ThomasKranitsas** [comment]
@birdofpreyru This ticket is ready for review :)

**Comment by birdofpreyru** [comment]
@ThomasKranitsas OK, great!
