### ISSUE TITLE
[$40] - Several fixes related to Join / Log In buttons in the top menu

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#940]
Log out of TopCoder, and open a challenge details page (e.g. https://www.topcoder.com/challenge-details/30056183/?type=develop). When the window is wide you see such header:
![tmp-1](https://cloud.githubusercontent.com/assets/20144632/22226231/e3cb1cea-e1c5-11e6-9466-35c931f86c7c.png)
Note that both JOIN and LOG IN buttons do redirect to the same login page. Correct the JOIN button to redirect to the proper endpoint page (https://accounts.topcoder.com/member/registration).
Now, check the same page in a narrow window:
![tmp-2](https://cloud.githubusercontent.com/assets/20144632/22226310/5058bd90-e1c6-11e6-942a-836a3a9a38eb.png)
You'll see that JOIN button is present, but differs in style from the wide-screen view, and is not functional, while the LOG IN button is missing. We should have here the same styled and functional buttons, as in the wide-screen view.

In case the header code is not found in this repo, then it should be here: https://github.com/appirio-tech/tc-site

**Comment by shubhendusaurabh** [comment]
@birdofpreyru please assign this to me. Thansk

**Comment by birdofpreyru** [comment]
@shubhendusaurabh OK.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru The login and register buttons actually hide under the dropdown in responsive mode. The login link appearing is extraneous. 
![buttons](https://cloud.githubusercontent.com/assets/1818387/22257493/43a5b4fe-e284-11e6-8ac5-333a0afa0ea4.png)

So expected fix for this would be to hide it and correct the endpoint for join button?

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Let's duplicate these buttons for now. I.e. those in the dropdown menu should remain and function as they do now, and you still add to the corner of the top menu these buttons looking and functioning similarly to how they do in the widescreen mode.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh OK. What you have done looks fine, but needs one additional thing: similar changes should be done in this repo: https://github.com/appirio-tech/tc-site which hosts the code for challenge listings and challenge details pages. It has its own copy of the header menu, which also should be corrected accordingly. Just add you changes in there, and we'll be done with this.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru see PR https://github.com/appirio-tech/tc-site/pull/459

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Can you further look into how this works in `tc-site` repo?

Your changes there looks to me like a movement in the right direction, but when I run that code locally, in the narrow screen view, the `Join` button does not work. The `Log in` button in the narrow screen mode, and both `Join` and `Log in` buttons in the wide screen mode do work, but they redirect to some other Login/Register pages (I guess, those are old, and not functional anymore). The reason for that is that they call not that version of `vm.login()` you have modified, but another one, defined in `tc-site/wp/wp-content/themes/tcs-responsive/footer.php`. I'd like you look further into that mess to understand, how it all works, and to fix it that it all works as it should. I'll bump the payment on this ticket.

P.S.: Are you testing with the locally deployed version of `tc-site`? If not, I believe, you really should. Though that Vagrant environment to run it locally, needs slight modifications to run, so if you have problems with that - just ask!

**Comment by shubhendusaurabh** [comment]
@birdofpreyru I have updated my PR. Thanks for the help, I have made the changes as per your info. 
Challenge details page uses the HTML version while rest of the pages use PHP version, so this fix should work now.
I had a previous vagrant setup, so I am using that. :)
