### ISSUE TITLE
[$5] - [Competitive Programming] - links are different when pages are loaded

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#944]
See this issue ticket: https://github.com/appirio-tech/tc-site/issues/438 (it is also valid with FireFox 50.1.0 on Ubuntu 16.04)

It looks to me, that if an URL contains a whitespace, it is a browser dependent thing, whether it is replaced by `%20` code, or not. At the same time, if we replaced the whitespace in that link with dash, I see that the URL
https://www.topcoder.com/community/competitive-programming/
serves the same page as 
https://www.topcoder.com/community/competitive programming/
or
https://www.topcoder.com/community/competitive%20programming/

### Expected Fix
Find all links to that Competitive Programming page both in this repo and in https://github.com/appirio-tech/tc-site and ensure that they use the endpoint with dash, rather than with whitespace or `%20`.

**Comment by harimp** [comment]
I'll take a look at this issue. Please assign this to me.

**Comment by birdofpreyru** [comment]
@harimp It is yours. Also I've send you invitation to the repo, so you can assign yourself, and change labels in future.

**Comment by harimp** [comment]
Thank you! 👍

**Comment by birdofpreyru** [comment]
@harimp There are also some links to correct in https://github.com/appirio-tech/tc-site, which has its own copy of the top menu. Please, correct them there as well.

**Comment by harimp** [comment]
I guess I missed something in review. I will get on it.

**Comment by harimp** [comment]
Added a pull request at https://github.com/appirio-tech/tc-site/pull/461.

**Comment by harimp** [comment]
Hi @birdofpreyru  I saw the announcement, but I couldn't submit a dummy submission to the TC challenge page. My TC username is harimp.

**Comment by birdofpreyru** [comment]
@harimp Oh, this is strange. Can you try once more?
If it still does not work for you, no worries, we'll sort it out.

**Comment by birdofpreyru** [comment]
@harimp Yeah, I got the problem: submission button is grey even though the submission phase is opened
Please, submit via OR: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30056206

**Comment by harimp** [comment]
Submitted it! Thank you.
