### ISSUE TITLE
[$5] - Missing Blog link in the menu

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#947]
Open www.topcoder.com and shrink the window to a small width. Open the dropdown main menu. Do you see the Blog link? No, but it is there! If you are lucky, you can even click on it and thus browse to the blog. A tiny CSS issue, I guess. Must be fixed.

![screen-3](https://cloud.githubusercontent.com/assets/20144632/22266933/28969d24-e282-11e6-9f9a-82ef155d51b2.png)

**Comment by rrandom** [comment]
please assign this to me

**Comment by birdofpreyru** [comment]
Hey @rrandom,
Please tell us, what is your TopCoder user handle, so that we can process the payment!

**Comment by birdofpreyru** [comment]
Or, better submit a dummy zip file to the challenge (we have temporarily re-opened submission phase for that).

**Comment by rrandom** [comment]
hi, @birdofpreyru  My Topcoder handle is somethin. Thanks!

**Comment by birdofpreyru** [comment]
@rrandom Can you submit a dummy solution to the challenge page? https://www.topcoder.com/challenge-details/30056206/?type=develop

**Comment by rrandom** [comment]
@birdofpreyru Sure! But the `Submit Your Entries` button in this page is gray. I cant submit

**Comment by birdofpreyru** [comment]
@rrandom 
Ohh... It looks like a small bug on the challenge page :)
Please, submit via OR: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30056206

**Comment by rrandom** [comment]
@birdofpreyru Done, thanks!
