### ISSUE TITLE
[$10] - Inconsistent top menu in various sections of the site, and also with different window size

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#952]
See the screenshot, and the last comment in the thread.

**Comment by birdofpreyru** [comment]
@ajefts 

I've noticed that the top menu for the narrow screen at the dashboard page (i.e. the one served by `topcoder-app`) contains a whole section of links missing in all other reincarnations of the top menu (wide screen from `topcoder-app` and both narrow and wide screen ones from `tc-site`):
![screen-4](https://cloud.githubusercontent.com/assets/20144632/22304536/1d8b644e-e338-11e6-9fc6-ffe5489f0558.png)

First, I want to check with you, whether it (1) was intended to be added everywhere, but somebody forgot to add it in all instances of the menu, or (2) was it intended to be removed, and somebody forgot to remove it from one of the places?

If (1), then to add these missing links to the widescreen menus, we'll need icons for these menu items.

**Comment by ajefts** [comment]
I think that was intentional since those links are in the footer...

**Comment by birdofpreyru** [comment]
### Expected Fix

This is a pretty easy one:
1. Remove this section from the narrow-screen menu (it is in this repo).
2. Ensure that the spacing between the last item in the menu (which will be `Blog` now) and the bottom of the grey background of the dropdown menu remains nice.
3. Check the menu at the challenge listing page (that menu is shown by the code in https://github.com/appirio-tech/tc-site), you'll see that there is no spacing between the last item in the menu, and its bottom border. Please fix it, so that both versions of the menu, served from different apps, do look like the same nice menu.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru Please elaborate on 2nd and 3rd requirements.
This is what the menu's are in app and site repos.

So, I need to match tc-site menu to topcoder-app menu? Add bottom padding in tc-site menu?

**Comment by birdofpreyru** [comment]
@shubhendusaurabh yes, the should be some bottom padding, the same in both repos. Now it is absent in `tc-site`
