### ISSUE TITLE
Copilot Profile Picture Resizing

### ISSUE THREAD

**Issue by vbaileytopcoder** [appirio-tech/topcoder-app#955]
Image resizing not working on profile pictures:

https://community.topcoder.com/tc?module=ViewCopilotPool&size=20&view=0&sort=12

**Comment by birdofpreyru** [comment]
@ajefts Which repo does host related code?

**Comment by ajefts** [comment]
@birdofpreyru That's part of what we call the "/tc" app, which is still in subversion:  https://coder.topcoder.com/internal/web_module/trunk/src/main/com/topcoder/web/tc/view/copilot/copilotPool.jsp

**Comment by Sande3p** [comment]
The fix is quit easy just 2 lines of css: https://gyazo.com/6470a4d65244caa952abc64735170d8c
```css  
  max-width: 140px;
  max-height: 140px;
```
But the biggest challenge is where to find _css/copilot-pool.css_  & redeploy to server

**Comment by birdofpreyru** [comment]
This .css file should be in the repo hosted in subversion.
So far I have not figured out how to deal with that (deployment of that for local testing is quite an adventure :)

**Comment by Sande3p** [comment]
how the get access to this repo?
few years ago I fixed some similar issue & tested JBoss.
to depoly used _ant buid_.
Not sure it's the same server or different

**Comment by birdofpreyru** [comment]
@Sande3p If you don't have access with your TC credentials via the link above, @ajefts can promote your permissions. Alternatively, I think I can upload a copy of that repo here to GitHub (but it surely will take some time).

Yeah, I've tried with `ant build` but it demanded some other code, which was not part of the repo, and I had not access to it back then. I got the access now, but have not tried again yet. I guess, after that there is a challenge how to configure that build to use the local Informix database, and how to set Informix up?

**Comment by Sande3p** [comment]
The above link only display a single page.
I think the style.jsp  contains desired server-path to the css file. https://gyazo.com/765dd6f932a78c304865ddac1a4819a1

**Comment by birdofpreyru** [comment]
@Sande3p Yeah, but you can explore the parent paths. Actually, the root of the repo is https://coder.topcoder.com/internal/web_module/trunk My experience with Subversion is about zero, but I've found that you may fetch it using `git svn` command (which works similar to usual `git`). It takes some time (few hours) to pull the whole repo, but then you can comfortably handle its local copy on your machine.

**Comment by Sande3p** [comment]
Is it possible to use winscp?
hostname? & port?

**Comment by birdofpreyru** [comment]
I don't know.

**Comment by Sande3p** [comment]
Finally I manage to checkout the code.
Do you think Tpocoder VM is required or we have to test it locally?

**Comment by birdofpreyru** [comment]
I don't know :) In fact, if you know about TopCoder VM, or local deployment of the code from that repo, you may instruct me how to do those ;)

**Comment by Sande3p** [comment]
I don't know much about the backed but I the contest spec. of this contest may help: 
https://www.topcoder.com/challenge-details/30053864/?type=develop

**Comment by vbaileytopcoder** [comment]
What is the status of this one @birdofpreyru? Thanks

**Comment by birdofpreyru** [comment]
@vbaileytopcoder No progress :( As you see above, the fix itself is clear and trivial, but I and participants who participated in the BugBash did not know how to build/test/contribute to the legacy TC site, which hosts the copilots listing.

I believe, @ajefts is aware of this situation, that there are multiple fixes and enhancements related to the that legacy TC site which community can do, if we get a brief on how-to deal with the existing codebase.

**Comment by birdofpreyru** [comment]
@ajefts A bit confused here I am.

To rapidly fix this one, I just need to introduce the change suggested by @Sande3p into `copilot-pool.css`, but I can't find any `*copilot-pool*` file in my clone of the Subversion repo. The only file with this name I see in the repos I have ever cloned so far is inside `tc1-tcnode` repo from Git, which you have told before, you don't really use.

**Comment by ajefts** [comment]
@birdofpreyru Since we like to confuse you, that's a legacy page and the css for it is in subversion:  https://coder.topcoder.com/internal/gd/trunk/website/tcdocs/css/

**Comment by birdofpreyru** [comment]
@ajefts Done - I've comitted the fix. Don't hesitate to tell, if I did anything wrong: my previous experience with Subversions is about zero.

**Comment by ajefts** [comment]
That did the trick :)

We didn't use proper branching, but it was a small fix so that's ok...

**Comment by ajefts** [comment]
I added a paid task in Direct for you.  Thanks!
