### ISSUE TITLE
[$40] - Add a COMPLETE APPEALS button when the appeals phase is open

### ISSUE THREAD

**Issue by ThomasKranitsas** [appirio-tech/topcoder-app#958]
Currently the **Appeals Phase** takes 24h and in most cases there are only few appeals.
Most members don't know or they just ignore the fact that they can actually click that button in the Online Review to close the Appeals phase sooner. 

I believe we should add a **Notification/link** on the challenge details page when the Appeals phase is open to tell the user that he/she can go and complete the appeals and close the phase sooner.

**Comment by birdofpreyru** [comment]
@ThomasKranitsas It is really cool you have remembered about this one!

As I believe it is more useful to have these links in the challenge cards in the Dashboard (and also somewhat easier to fit them there in a pretty way), let's start with that one.

In the Grid view it should look like this:
![screen-5](https://cloud.githubusercontent.com/assets/20144632/22345517/a8444be6-e400-11e6-910a-7e5aa23fabf6.png)

`View Scorecards` button should become blue with white text when hovered and it should lead to the OR page with scorecards and appeals.

`Complete Appeals` button should become red with white text (the same tint of red, as the unregister button in the challenge details page has) when hovered. Also, probably, it will be handier, if it has red text and border in the normal state. This should lead to the complete appeals confirmation page in OR.

If appeals are completed, but the appeals phase is not over yet, we should have the `Resume appeals` buttons, styled in the blue colors. That one, if possible, should directly resume reappeals in the OR. No need for extra confirmation.

`View Scorecards` button should be also visible during the appeal responses phase.

I believe, that the same card component is re-used to show past and drafted challenges, so be sure that your changes don't have any negative impact there.

Also, for the completed challenges, I think we can add `Results` button in bluish style, which should lead directly to the challenge winners page in the challenge details.

As there is also List view, similar changes should be done there:
![screen-6](https://cloud.githubusercontent.com/assets/20144632/22345773/c58448ea-e401-11e6-8667-741f2d584b49.png)

**Comment by ThomasKranitsas** [comment]
Is that possible to have a test challenge in Appeals phase so I can test it?

And also have the member `dan_developer/dantopcoder123` registered to that challenge?

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Sure, it is possible, but I don't know how to do it yet. 
@ajefts please help

**Comment by ThomasKranitsas** [comment]
@birdofpreyru @ajefts any update?

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Not from my side.

Well, in the mean time you may try to tweak the frontend code to work against the production database and to fetch `my-challenges` for a user different from the logged in one.

To achieve that you go to
`/topcoder-app/node_modules/appirio-tech-webpack-config/constants.coffee`
and in the `DEV` section of constants you change `API_URL` and `API_URL_V2` removing `-dev` part from them. Then you search for `vm.handle` in the Dashboard controller and replace it with your, or somebody's else handle. After that it will show you somebody else dashboard, and if it has challenges in appeals phase, you can test :)
