### ISSUE TITLE
[$20] - Sitemap, About Us, Contact Us, etc. links in the narrow screen view

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#967]
Look at the footer when the site is open in a wide window:
![scr-1](https://cloud.githubusercontent.com/assets/20144632/22406811/f7518748-e659-11e6-9ff8-ec7a77a91e24.png)

Now, look at the footer when the site is open in a narrow window:
![scr-2](https://cloud.githubusercontent.com/assets/20144632/22406814/02dac9f8-e65a-11e6-8593-b55b4cfabef2.png)

You see, that the links `Sitemap`, `About Us`, `Contact Us`, ... are missing, also the social network icons are grey in the narrow view vs. colored in the wide view, and also the copyright line is gray in the narrow screen, while wide in the wide screen.

All this should be fixed in the narrow-screen view to be consistent with the wide-screen view, to look like this (sure, the spacings between the elements should be nice and equal, excuse my poor drawing skills):
![scr-3](https://cloud.githubusercontent.com/assets/20144632/22406832/6e859174-e65a-11e6-9176-ba18ababe641.png)

This issue should be fixed both in this repo, and in the https://github.com/appirio-tech/tc-site
I believe, this is a purely CSS fix, as the relevant links are present in the HTML markup, just not shown in the narrow-size window

**Comment by ThomasKranitsas** [comment]
@birdofpreyru I'll work on this one :)

**Comment by birdofpreyru** [comment]
@ThomasKranitsas This needs the following changes:

1. Remove the `OTHERS` title, and ensure there is a bit larger padding between the top of the footer and the first link (`SITEMAP`).
2. Make the color of these footer links white (the same white as in the wide-screen view), and blue when hovered.
3. Decrease the spacing between social icons and `(C) 2016 Topcoder. All Rights Reserved`. Like twice smaller.

Also add similar changes into this repo,

**Comment by birdofpreyru** [comment]
@ThomasKranitsas Any update?

**Comment by ThomasKranitsas** [comment]
I'll submit PR later today. sorry for delay

**Comment by lijulat** [comment]
@birdofpreyru Is there anythign pending on this ticket?

**Comment by birdofpreyru** [comment]
@lijulat Yes, check the comments in this PR: https://github.com/appirio-tech/topcoder-app/pull/978
It almost does what is necessary, but breaks the build, and it should be fixed

I believe, what @ThomasKranitsas did already, cost $20.
So, I'd say fixing the last small issues will cost $10, what do you think?

**Comment by lijulat** [comment]
@birdofpreyru let me give me it a try.

**Comment by lijulat** [comment]
@birdofpreyru should i update the PR or raise a fresh PR
