### ISSUE TITLE
[$5] - Forum link on challenge details page for reviewers

### ISSUE THREAD

**Issue by ThomasKranitsas** [appirio-tech/topcoder-app#969]
When I'm registered on a challenge with a `reviewer` role I can't access the challenge forum from the challenge details page. I have to either click the **Forum** link from OR or click the forum **icon** from the challenge card in the dashboard page.

Also in the challenge details page there are register/submit buttons which don't make sense for reviewers.

Check screenshot: http://take.ms/7omMo

**Comment by iversonLv** [comment]
I remembered I discuss such case with @adroc who say there is something privacy policy for the flow.
So reviewer must access OR then forum not from detail page.

More info might need TC admin clarification.

**Comment by birdofpreyru** [comment]
@ThomasKranitsas @iversonLv I agree, we can fix it, both looks like small frontend issues (just slight modifications of conditions for showing the buttons and links are necessary, and the info about your roles in a challenge, I guess, already is loaded into the controller). I'd say this is a $10 job. The only thing, I'm not sure yet how to test it.

**Comment by birdofpreyru** [comment]
### Expected Fix

We are ready to enhance it. First, have a look at this PR: https://github.com/appirio-tech/tc-site/pull/479, it implements the loading of user roles into the controller of Challenge Details page, and provides an auxilary function to check the roles.

You should use this to change the logic behind showing/hiding the link to challenge forum at the Challenge Details page. The link should be visible for users with the following roles: `Submitter`, `Copilot`, `Reviewer`, `Approver`. I have not checked it, but I suspect, that when a user is not logged in, or not registered for a challenge, the array of roles in the controller will be just empty. If this is the case, then we can just show the link if he has any role in the challenge.

Related code is hosted in https://github.com/appirio-tech/tc-site
