### ISSUE TITLE
[$5] - Add option to use new listings page

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#971]
As we get make progress on the new challenge listings experience, let's add a link to the new experience from the existing challenge listings page.  It should be something at the top that directs to user to try to new experience at www.topcoder.com/listings.

**Comment by ajefts** [comment]
@birdofpreyru Can you add this one to the list?  I don't have a design for it, but I was hoping you guys could come up with something clean and simple.  This should just link people to the new experience, and not set any kind of preference.

Thanks.

**Comment by birdofpreyru** [comment]
@ajefts Sure! Does it look fine to you, if we store selected option in the user browser's `localStorage`, and thus keep all changes at the frontend side, without messing with the backend?

**Comment by birdofpreyru** [comment]
@ajefts Sorry, I have not read you previous msg carefully enough. So, just a link to the new listing, not a switch, no need to store the choice at all?

**Comment by birdofpreyru** [comment]
### Expected Fix
In all current challenge listing pages (design, development, data science, served by the code in https://github.com/appirio-tech/tc-site) add under the title the link to the new challenge listings (`/listings` endpoint), like so:
![scr-12](https://cloud.githubusercontent.com/assets/20144632/22656176/cc7c528e-ec92-11e6-9568-293e888fd42f.png)
The link text reads `Get a glimpse of the new challenge listing page (alpha version)`.
The style (color, font size) of the link should match the one of `Past Challenges`, `Upcoming Challenges`, `Review`, and the `(alpha version)` part should be a superscript.

**Comment by ajefts** [comment]
That works for me.  Thanks!
