### ISSUE TITLE
[$20] - Remove extra marketing tags

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/topcoder-app#979]
We have marketo and adroll but don't use them anymore on pages like https://www.topcoder.com/challenges please remove them

FYI

<script type="text/javascript">
adroll_adv_id = "LOUA2FVRTJDYZC2BMX72Z7";
adroll_pix_id = "4XU6H3BYL5EQBFHZM4DIUU";
(function () {
var oldonload = window.onload;
window.onload = function(){
   __adroll_loaded=true;
   var scr = document.createElement("script");
   var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
   scr.setAttribute('async', 'true');
   scr.type = "text/javascript";
   scr.src = host + "/j/roundtrip.js";
   ((document.getElementsByTagName('head') || [null])[0] ||
    document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
   if(oldonload){oldonload()}};
}());
</script>

<script type="text/javascript">
document.write(unescape("%3Cscript src='//munchkin.marketo.net/munchkin.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script>Munchkin.init('921-UOU-112', {"wsInfo":"jFRS"});</script>

**Comment by dmessing** [comment]
@birdofpreyru this might be an easy one to get tossed in

**Comment by birdofpreyru** [comment]
### Expected Fix

Remove the mentioned `marketo` and `adroll` scripts from the pages served both from this repo, and from https://github.com/appirio-tech/tc-site, and ensure, that it does not break anything.

**Comment by lijulat** [comment]
Can I try to fix ?

**Comment by birdofpreyru** [comment]
@lijulat Sure! It is yours.

**Comment by birdofpreyru** [comment]
@lijulat Also remove the `KISSmetrics` scripts from both repos. As you remember, you have added this script to `tc-site` earlier to fix the missing user menu (https://github.com/appirio-tech/topcoder-app/issues/932) it turns out, that this analytics is not used anymore, so should be removed, and all references to it should be properly cleaned out, in the way that nothing is broken as that menu.

**Comment by birdofpreyru** [comment]
@lijulat Any update?

**Comment by lijulat** [comment]
@birdofpreyru Apologies will raise a PR soon

**Comment by lijulat** [comment]
@birdofpreyru A quick question should google analytics stay?

**Comment by birdofpreyru** [comment]
@lijulat Yeap, as it was never mentioned to remove it, I guess Google.Analytics should stay.

**Comment by lijulat** [comment]
@birdofpreyru #471 PR on the TC-site repo

**Comment by birdofpreyru** [comment]
@lijulat Ok, will check it later.
Don't forget that we also need to remove them from the code in this repo as well.

**Comment by lijulat** [comment]
@birdofpreyru PR coming your way  :) .  Can i delete the js file  or should i keep the js file and remove the contents? . Just asking ,because kissmetrics the js file is presetnt with no contents still in the repo,

**Comment by birdofpreyru** [comment]
@lijulat Please remove them completely, just double check that nothing else refer to them
