### ISSUE TITLE
[$5] - Change the styling of the PLATFORMS list in the Challenge Specs page

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#980]
The code is in https://github.com/appirio-tech/tc-site
Here is the sample Challenge Specs page: http://www.topcoder.com/challenge-details/30056243/?type=develop&noncache=true

You'll see there that `PLATFORMS` and `TECHNOLOGIES` lists are styled differently:
![0b2afa36-ea03-11e6-9840-8f4d1d367fc1](https://cloud.githubusercontent.com/assets/20144632/22599510/8488c488-ea37-11e6-9cb3-0e94b7ae6bfe.png)

Please change the styling of `PLATFORMS` list to be the same as the styling of `TECHNOLOGIES` list.

**Comment by gets0ul** [comment]
New commit has been added.
