### ISSUE TITLE
[$10] - /my-dashboard ENDS IN time counter issue

### ISSUE THREAD

**Issue by rainerlopez** [appirio-tech/topcoder-app#984]
ref: https://www.topcoder.com/my-dashboard/
After reaching 0 (zero) the counter starts counting backwards (increasing the time).

image ref: https://drive.google.com/file/d/0Bxt92xXpPQgCeUpwWTFYM3lZbTg/view?usp=sharing
_The screening phase had already ended (reached zero) when the print screen was taken_

**Comment by birdofpreyru** [comment]
### Expected Fix
When a phase is late (I guess, API returns a negative time till the end in that case), we should the following in the Grid view (please, discount for my poor Photoshop skills):
![scr-10](https://cloud.githubusercontent.com/assets/20144632/22648889/eb379554-ec78-11e6-97f3-35efe4919d0d.png)
I.e. we change the label above the time box from `ENDS IN` for `LATE FOR`, and we chance the color of that label and the number in the box from grey to reddish (`#ee6666`). Other styling (fonts, etc.) should stay the same.

In the list view, if a phase is late, we just change the color of the end phase time from gray to reddish (`#ee6666`), like so:
![scr-11](https://cloud.githubusercontent.com/assets/20144632/22649032/8cde1d06-ec79-11e6-8558-8ee132bbe994.png)
