### ISSUE TITLE
Topcoder Blitz broken link

### ISSUE THREAD

**Issue by rainerlopez** [appirio-tech/topcoder-app#985]
ref: http://blitz.topcoder.com/hpe-lpc_build/
image ref: https://drive.google.com/file/d/0Bxt92xXpPQgCZUNJaUUxUGpWbjQ/view?usp=sharing

The [Topcoder Blitz](https://help.topcoder.com/general-help/member-bonuses/topcoder-blitz/) link at the end of http://blitz.topcoder.com/hpe-lpc_build/ page links to https://help.topcoder.com/general-help/member-bonuses/topcoder-blitz/ that is displaying:

"_oops
The page you were looking for doesn't exist
You may have mistyped the address or the page may have moved_"

**Google Chrome 55.0.2883.87 m
Windows 10 Pro**

**Comment by birdofpreyru** [comment]
This is right, but probably can be just ignored: the Blitz is almost finished, and the link is not that important, so does not look very beneficial to spend time on fixing it.
