### ISSUE TITLE
[$10] - add iOS badge to badge sprite

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#987]
Add the iOS participant badge to the badge sprite.  The badge is currently shown here:  https://ios.topcoder.com/badges

https://ios.topcoder.com/content/images/svg/Member-06.cad2892e.svg

**Comment by ajefts** [comment]
@birdofpreyru Here is another one.

**Comment by ajefts** [comment]
fyi @dmessing

**Comment by birdofpreyru** [comment]
### Expected Fix

Add the badge to the sprite. Recently we have added Predix Community badge to the sprite, please check these closed issue and PR: https://github.com/appirio-tech/topcoder-app/issues/912, https://github.com/appirio-tech/topcoder-app/pull/953 and do the same with the new badge.

If @ajefts won't say differently before you fix this issue, use `iOS Community` name for the badge.
