### ISSUE TITLE
[$10] - Inactive submission button at the Challenge Specs page, when submission phase is late.

### ISSUE THREAD

**Issue by birdofpreyru** [appirio-tech/topcoder-app#990]
When submission phase is late (i.e. we are past the deadline for submission, but the submission phase has been re-opened by admin for some very special reason, to allow somebody to contribute past the deadline), the `Submit` button at the Challenge Specs page remains inactive. Submission through the OR page is available though.

We should modify the button logic to be active whenever the submission phase is open.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru Any test challenge active currently with above conditions?

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Nope, I've tried to rapidly create one for the remote dev env, but failed :( I believe though, this one might be a simple fix, which we can do without test. Most probably, the button condition checks that challenge phase is Submission, and the time till the end of the phase is positive, thus we only need to remove the second condition.

I'll look more into creating of the test challenge tomorrow.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru current logic is simply to check if `submissionEndDate` is positive and the user has registered to the challenge.
It would be better to check what's causing that issue and then fix that.

**Comment by birdofpreyru** [comment]
@ajefts Can you help me a bit here? I don't know how to make a mock billing account in `www.topcoder-dev.com/direct`, and without billing account development version of Direct does not allow to activate challenges.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh 
FYI: I believe, using this https://github.com/appirio-tech/tc-common-tutorials, especially `docker/direct-app` folder there, you can setup locally everything necessary to test challenge-phases-related functionality. I have not yet tried it now, but I believe, I was using that in some challenge a while ago, and it was working like a charm (after you make it through the setup :)

**Comment by birdofpreyru** [comment]
### Update
Test challenge set up at dev site: https://www.topcoder-dev.com/challenge-details/30050681/?type=develop&noncache=true. Submission phase is manually set open, but it is late (phase end date is in the past already).
`dan_developer` test user is registered to the challenge as competitor. He can upload submission using Online Review, but he can't from the challenge details page, as the button is inactive.
